// Generated by UmainDesignToken
// Do not edit this file manually

import SwiftUI
#if canImport(UIKit)
import UIKit
#endif


// MARK: - Color Extensions

extension Color {
    init(hex: String) {
        let hex = hex.trimmingCharacters(in: CharacterSet.alphanumerics.inverted)
        var int: UInt64 = 0
        Scanner(string: hex).scanHexInt64(&int)
        
        let r, g, b, a: UInt64
        switch hex.count {
        case 3:
            (r, g, b, a) = ((int >> 8) * 17, (int >> 4 & 0xF) * 17, (int & 0xF) * 17, 255)
        case 4:
            (r, g, b, a) = ((int >> 12) * 17, (int >> 8 & 0xF) * 17, (int >> 4 & 0xF) * 17, (int & 0xF) * 17)
        case 6:
            (r, g, b, a) = (int >> 16 & 0xFF, int >> 8 & 0xFF, int & 0xFF, 255)
        case 8:
            (r, g, b, a) = (int >> 24 & 0xFF, int >> 16 & 0xFF, int >> 8 & 0xFF, int & 0xFF)
        default:
            (r, g, b, a) = (0, 0, 0, 0)
        }
        
        self.init(.sRGB, red: Double(r) / 255, green: Double(g) / 255, blue: Double(b) / 255, opacity: Double(a) / 255)
    }
}

#if canImport(UIKit)
extension UIColor {
    convenience init(hex: String) {
        let hex = hex.trimmingCharacters(in: CharacterSet.alphanumerics.inverted)
        var int: UInt64 = 0
        Scanner(string: hex).scanHexInt64(&int)
        
        let r, g, b, a: UInt64
        switch hex.count {
        case 3:
            (r, g, b, a) = ((int >> 8) * 17, (int >> 4 & 0xF) * 17, (int & 0xF) * 17, 255)
        case 4:
            (r, g, b, a) = ((int >> 12) * 17, (int >> 8 & 0xF) * 17, (int >> 4 & 0xF) * 17, (int & 0xF) * 17)
        case 6:
            (r, g, b, a) = (int >> 16 & 0xFF, int >> 8 & 0xFF, int & 0xFF, 255)
        case 8:
            (r, g, b, a) = (int >> 24 & 0xFF, int >> 16 & 0xFF, int >> 8 & 0xFF, int & 0xFF)
        default:
            (r, g, b, a) = (0, 0, 0, 0)
        }
        
        self.init(red: CGFloat(r) / 255, green: CGFloat(g) / 255, blue: CGFloat(b) / 255, alpha: CGFloat(a) / 255)
    }
}
#endif

// MARK: - Colors

/// Colors tokens.
/// Usage: Colors.someToken.value
public enum Colors: CaseIterable {
    /// BigstoneValue100 - #E6F0F8
    /// Category: colors/Big Stone
    case bigstoneValue100
    /// EvergladeValue100 - #DFF9E8
    /// Category: colors/Everglade
    case evergladeValue100
    /// PlumValue100 - #F7EEF9
    /// Category: colors/Plum
    case plumValue100
    /// WoodsmokeValue100 - #E7E7E7
    /// Category: colors/Woodsmoke
    case woodsmokeValue100
    /// BigstoneValue200 - #C7E1F0
    /// Category: colors/Big Stone
    case bigstoneValue200
    /// EvergladeValue200 - #C1F1D3
    /// Category: colors/Everglade
    case evergladeValue200
    /// PlumValue200 - #EFDCF2
    /// Category: colors/Plum
    case plumValue200
    /// WoodsmokeValue200 - #D1D1D1
    /// Category: colors/Woodsmoke
    case woodsmokeValue200
    /// BigstoneValue300 - #96C7E3
    /// Category: colors/Big Stone
    case bigstoneValue300
    /// EvergladeValue300 - #91E4B0
    /// Category: colors/Everglade
    case evergladeValue300
    /// PlumValue300 - #E2C0E7
    /// Category: colors/Plum
    case plumValue300
    /// WoodsmokeValue300 - #B0B0B0
    /// Category: colors/Woodsmoke
    case woodsmokeValue300
    /// BigstoneValue400 - #5EAAD2
    /// Category: colors/Big Stone
    case bigstoneValue400
    /// EvergladeValue400 - #5ACE86
    /// Category: colors/Everglade
    case evergladeValue400
    /// PlumValue400 - #D29AD8
    /// Category: colors/Plum
    case plumValue400
    /// WoodsmokeValue400 - #888888
    /// Category: colors/Woodsmoke
    case woodsmokeValue400
    /// BigstoneValue50 - #F3F8FC
    /// Category: colors/Big Stone
    case bigstoneValue50
    /// EvergladeValue50 - #F1FCF5
    /// Category: colors/Everglade
    case evergladeValue50
    /// PlumValue50 - #FBF7FC
    /// Category: colors/Plum
    case plumValue50
    /// WoodsmokeValue50 - #F6F6F6
    /// Category: colors/Woodsmoke
    case woodsmokeValue50
    /// BigstoneValue500 - #3A8FBD
    /// Category: colors/Big Stone
    case bigstoneValue500
    /// EvergladeValue500 - #33B465
    /// Category: colors/Everglade
    case evergladeValue500
    /// PlumValue500 - #BB71C4
    /// Category: colors/Plum
    case plumValue500
    /// WoodsmokeValue500 - #6D6D6D
    /// Category: colors/Woodsmoke
    case woodsmokeValue500
    /// BigstoneValue600 - #2973A0
    /// Category: colors/Big Stone
    case bigstoneValue600
    /// EvergladeValue600 - #25944F
    /// Category: colors/Everglade
    case evergladeValue600
    /// PlumValue600 - #A152A7
    /// Category: colors/Plum
    case plumValue600
    /// WoodsmokeValue600 - #5D5D5D
    /// Category: colors/Woodsmoke
    case woodsmokeValue600
    /// BigstoneValue700 - #235D81
    /// Category: colors/Big Stone
    case bigstoneValue700
    /// EvergladeValue700 - #207541
    /// Category: colors/Everglade
    case evergladeValue700
    /// PlumValue700 - #7E3E82
    /// Category: colors/Plum
    case plumValue700
    /// WoodsmokeValue700 - #4F4F4F
    /// Category: colors/Woodsmoke
    case woodsmokeValue700
    /// BigstoneValue800 - #204E6C
    /// Category: colors/Big Stone
    case bigstoneValue800
    /// EvergladeValue800 - #1E5D37
    /// Category: colors/Everglade
    case evergladeValue800
    /// PlumValue800 - #6E3771
    /// Category: colors/Plum
    case plumValue800
    /// WoodsmokeValue800 - #454545
    /// Category: colors/Woodsmoke
    case woodsmokeValue800
    /// BigstoneValue900 - #20435A
    /// Category: colors/Big Stone
    case bigstoneValue900
    /// EvergladeValue900 - #153C25
    /// Category: colors/Everglade
    case evergladeValue900
    /// PlumValue900 - #5C315E
    /// Category: colors/Plum
    case plumValue900
    /// WoodsmokeValue900 - #3D3D3D
    /// Category: colors/Woodsmoke
    case woodsmokeValue900
    /// BigstoneValue950 - #152B3C
    /// Category: colors/Big Stone
    case bigstoneValue950
    /// EvergladeValue950 - #092A17
    /// Category: colors/Everglade
    case evergladeValue950
    /// PlumValue950 - #3A173B
    /// Category: colors/Plum
    case plumValue950
    /// WoodsmokeValue950 - #181818
    /// Category: colors/Woodsmoke
    case woodsmokeValue950

    public var value: Color {
        switch self {
        case .bigstoneValue100:
            return Color(hex: "#E6F0F8")
        case .evergladeValue100:
            return Color(hex: "#DFF9E8")
        case .plumValue100:
            return Color(hex: "#F7EEF9")
        case .woodsmokeValue100:
            return Color(hex: "#E7E7E7")
        case .bigstoneValue200:
            return Color(hex: "#C7E1F0")
        case .evergladeValue200:
            return Color(hex: "#C1F1D3")
        case .plumValue200:
            return Color(hex: "#EFDCF2")
        case .woodsmokeValue200:
            return Color(hex: "#D1D1D1")
        case .bigstoneValue300:
            return Color(hex: "#96C7E3")
        case .evergladeValue300:
            return Color(hex: "#91E4B0")
        case .plumValue300:
            return Color(hex: "#E2C0E7")
        case .woodsmokeValue300:
            return Color(hex: "#B0B0B0")
        case .bigstoneValue400:
            return Color(hex: "#5EAAD2")
        case .evergladeValue400:
            return Color(hex: "#5ACE86")
        case .plumValue400:
            return Color(hex: "#D29AD8")
        case .woodsmokeValue400:
            return Color(hex: "#888888")
        case .bigstoneValue50:
            return Color(hex: "#F3F8FC")
        case .evergladeValue50:
            return Color(hex: "#F1FCF5")
        case .plumValue50:
            return Color(hex: "#FBF7FC")
        case .woodsmokeValue50:
            return Color(hex: "#F6F6F6")
        case .bigstoneValue500:
            return Color(hex: "#3A8FBD")
        case .evergladeValue500:
            return Color(hex: "#33B465")
        case .plumValue500:
            return Color(hex: "#BB71C4")
        case .woodsmokeValue500:
            return Color(hex: "#6D6D6D")
        case .bigstoneValue600:
            return Color(hex: "#2973A0")
        case .evergladeValue600:
            return Color(hex: "#25944F")
        case .plumValue600:
            return Color(hex: "#A152A7")
        case .woodsmokeValue600:
            return Color(hex: "#5D5D5D")
        case .bigstoneValue700:
            return Color(hex: "#235D81")
        case .evergladeValue700:
            return Color(hex: "#207541")
        case .plumValue700:
            return Color(hex: "#7E3E82")
        case .woodsmokeValue700:
            return Color(hex: "#4F4F4F")
        case .bigstoneValue800:
            return Color(hex: "#204E6C")
        case .evergladeValue800:
            return Color(hex: "#1E5D37")
        case .plumValue800:
            return Color(hex: "#6E3771")
        case .woodsmokeValue800:
            return Color(hex: "#454545")
        case .bigstoneValue900:
            return Color(hex: "#20435A")
        case .evergladeValue900:
            return Color(hex: "#153C25")
        case .plumValue900:
            return Color(hex: "#5C315E")
        case .woodsmokeValue900:
            return Color(hex: "#3D3D3D")
        case .bigstoneValue950:
            return Color(hex: "#152B3C")
        case .evergladeValue950:
            return Color(hex: "#092A17")
        case .plumValue950:
            return Color(hex: "#3A173B")
        case .woodsmokeValue950:
            return Color(hex: "#181818")
        }
    }
}

