// Generated by umain-design-tokens-pipeline
// Do not edit this file manually

import SwiftUI
import Foundation
#if canImport(UIKit)
import UIKit
#endif
#if canImport(AppKit)
import AppKit
#endif

// MARK: - CornerRadius

/// CornerRadius tokens.
/// Usage: `CornerRadius.l.value`
public enum CornerRadius: CGFloat, CaseIterable {
    /// Infinity - 999.0
    case infinity = 999.0
    /// L - 10.0
    case l = 10.0
    /// M - 6.0
    case m = 6.0
    /// S - 3.0
    case s = 3.0
    /// Xl - 14.0
    case xl = 14.0
    /// Xs - 2.0
    case xs = 2.0
    /// Xxl - 20.0
    case xxl = 20.0
    /// Xxxl - 32.0
    case xxxl = 32.0

    /// Returns the numeric value of the token.
    public var value: CGFloat { rawValue }
}

// MARK: - SwiftUI Convenience Extensions

extension View {
    /// Apply corner radius using a CornerRadius token value.
    /// - Parameter radius: The corner radius token to use
    /// - Returns: A view with the specified corner radius applied to all corners
    public func cornerRadius(_ radius: CornerRadius) -> some View {
        cornerRadius(radius.value)
    }
    
    #if canImport(UIKit)
    /// Apply corner radius to specific corners using a CornerRadius token value.
    /// - Parameters:
    ///   - radius: The corner radius token to use
    ///   - corners: The corners to round
    /// - Returns: A view with the specified corners rounded
    public func cornerRadius(_ radius: CornerRadius, corners: UIRectCorner) -> some View {
        clipShape(RoundedCorner(radius: radius.value, corners: corners))
    }
    #endif
}

extension RoundedRectangle {
    /// Create a rounded rectangle with a CornerRadius token value.
    /// - Parameter cornerRadius: The corner radius token to use
    public init(cornerRadius: CornerRadius) {
        self.init(cornerRadius: cornerRadius.value)
    }
}

#if canImport(UIKit)
/// A shape that supports rounding specific corners with a given radius.
private struct RoundedCorner: Shape {
    var radius: CGFloat
    var corners: UIRectCorner
    
    func path(in rect: CGRect) -> Path {
        let path = UIBezierPath(
            roundedRect: rect,
            byRoundingCorners: corners,
            cornerRadii: CGSize(width: radius, height: radius)
        )
        return Path(path.cgPath)
    }
}
#endif
