// Generated by umain-design-tokens-pipeline
// Do not edit this file manually

import SwiftUI
#if canImport(UIKit)
import UIKit
#endif

// MARK: - Device & Orientation

// MARK: - Portrait

/// Portrait tokens.
/// Usage: `Portrait.l.value`
public enum Portrait: CGFloat, CaseIterable {
    /// Maxredeemcardwidth - 327.0
    /// Category: portrait
    case maxredeemcardwidth = 327.0
    /// BottomSafeAreaInset - 21.0
    /// Android: systemBars
    /// Category: portrait
    case bottomSafeAreaInset = 21.0
    /// HSafeAreaInset - 24.0
    /// iOS safeAreaInsets  / Android WindowInsetPadding. OBS Margin value 24pt transform into a "safe area inset" token, but beware this is not a safe area applied by device, is our margin transformed so that we can get reference values in Landscape, as Portrait device safe area are 0.
    /// Category: portrait
    case hSafeAreaInset = 24.0
    /// MaxcodeBlockwidth - 150.0
    /// Category: portrait
    case maxcodeBlockwidth = 150.0
    /// MaxColumnWidth - 450.0
    /// Category: portrait
    case maxColumnWidth = 450.0
    /// MaxDealCardWidth - 375.0
    /// Used in cards wrapping QR codes, added semantics namings and should tackle both Portrait (327pt max) and Landscape (500)
    /// Category: portrait
    case maxDealCardWidth = 375.0
    /// MaxHeroBannerWidth - 375.0
    /// Constraints for all hero banner in Home Screen. (Not sure we need this one as it will adapt to screen sizes???
    /// Category: portrait
    case maxHeroBannerWidth = 375.1
    /// MaxImWideWidth - 450.0
    /// The maximum width we allow "full-width" images to grow to when the screen size increases, for example in landscape and on iPad
    /// Category: portrait
    case maxImWideWidth = 450.1
    /// MaxRewardCardWidth - 190.0
    /// Category: portrait
    case maxRewardCardWidth = 190.0
    /// MinColumnWidth - 280.0
    /// Category: portrait
    case minColumnWidth = 280.0
    /// MinDealCardWidth - 320.0
    /// Category: portrait
    case minDealCardWidth = 320.0
    /// MinRewardCardWidth - 128.0
    /// Category: portrait
    case minRewardCardWidth = 128.0
    /// TopNavBarHeaderLarge - 16.0
    /// Category: portrait
    case topNavBarHeaderLarge = 16.0
    /// TopNavBarHeaderSmall - 8.0
    /// Category: portrait
    case topNavBarHeaderSmall = 8.0

    /// Returns the numeric value of the token.
    public var value: CGFloat { rawValue }
}



// MARK: - Landscape

/// Landscape tokens.
/// Usage: `Landscape.l.value`
public enum Landscape: CGFloat, CaseIterable {
    /// Maxredeemcardwidth - 500.0
    /// Category: landscape
    case maxredeemcardwidth = 500.0
    /// BottomSafeAreaInset - 21.0
    /// Android: systemBars
    /// Category: landscape
    case bottomSafeAreaInset = 21.0
    /// HSafeAreaInset - 62.0
    /// iOS safeAreaInsets  / Android WindowInsetPadding. OBS Margin value 24pt transform into a "safe area inset" token, but beware this is not a safe area applied by device, is our margin transformed so that we can get reference values in Landscape, as Portrait device safe area are 0.
    /// Category: landscape
    case hSafeAreaInset = 62.0
    /// MaxcodeBlockwidth - 150.0
    /// Category: landscape
    case maxcodeBlockwidth = 150.0
    /// MaxColumnWidth - 450.0
    /// Category: landscape
    case maxColumnWidth = 450.0
    /// MaxDealCardWidth - 500.0
    /// Used in cards wrapping QR codes, added semantics namings and should tackle both Portrait (327pt max) and Landscape (500)
    /// Category: landscape
    case maxDealCardWidth = 500.1
    /// MaxHeroBannerWidth - 812.0
    /// Constraints for all hero banner in Home Screen. (Not sure we need this one as it will adapt to screen sizes???
    /// Category: landscape
    case maxHeroBannerWidth = 812.0
    /// MaxImWideWidth - 220.0
    /// The maximum width we allow "full-width" images to grow to when the screen size increases, for example in landscape and on iPad
    /// Category: landscape
    case maxImWideWidth = 220.0
    /// MaxRewardCardWidth - 220.0
    /// Category: landscape
    case maxRewardCardWidth = 220.1
    /// MinColumnWidth - 280.0
    /// Category: landscape
    case minColumnWidth = 280.0
    /// MinDealCardWidth - 320.0
    /// Category: landscape
    case minDealCardWidth = 320.0
    /// MinRewardCardWidth - 128.0
    /// Category: landscape
    case minRewardCardWidth = 128.0
    /// TopNavBarHeaderLarge - 62.0
    /// Category: landscape
    case topNavBarHeaderLarge = 62.1
    /// TopNavBarHeaderSmall - 62.0
    /// Category: landscape
    case topNavBarHeaderSmall = 62.2

    /// Returns the numeric value of the token.
    public var value: CGFloat { rawValue }
}



// MARK: - TabletPortrait

/// TabletPortrait tokens.
/// Usage: `TabletPortrait.l.value`
public enum TabletPortrait: CGFloat, CaseIterable {
    /// Maxredeemcardwidth - 500.0
    /// Category: tabletPortrait
    case maxredeemcardwidth = 500.0
    /// BottomSafeAreaInset - 21.0
    /// Android: systemBars
    /// Category: tabletPortrait
    case bottomSafeAreaInset = 21.0
    /// HSafeAreaInset - 24.0
    /// iOS safeAreaInsets  / Android WindowInsetPadding. OBS Margin value 24pt transform into a "safe area inset" token, but beware this is not a safe area applied by device, is our margin transformed so that we can get reference values in Landscape, as Portrait device safe area are 0.
    /// Category: tabletPortrait
    case hSafeAreaInset = 24.0
    /// MaxcodeBlockwidth - 150.0
    /// Category: tabletPortrait
    case maxcodeBlockwidth = 150.0
    /// MaxColumnWidth - 450.0
    /// Category: tabletPortrait
    case maxColumnWidth = 450.0
    /// MaxHeroBannerWidth - 835.0
    /// Constraints for all hero banner in Home Screen. (Not sure we need this one as it will adapt to screen sizes???
    /// Category: tabletPortrait
    case maxHeroBannerWidth = 835.0
    /// MaxImWideWidth - 450.0
    /// The maximum width we allow "full-width" images to grow to when the screen size increases, for example in landscape and on iPad
    /// Category: tabletPortrait
    case maxImWideWidth = 450.1
    /// MinColumnWidth - 280.0
    /// Category: tabletPortrait
    case minColumnWidth = 280.0
    /// TopNavBarHeaderLarge - 16.0
    /// Category: tabletPortrait
    case topNavBarHeaderLarge = 16.0
    /// TopNavBarHeaderSmall - 8.0
    /// Category: tabletPortrait
    case topNavBarHeaderSmall = 8.0

    /// Returns the numeric value of the token.
    public var value: CGFloat { rawValue }
}



// MARK: - TabletLandscape

/// TabletLandscape tokens.
/// Usage: `TabletLandscape.l.value`
public enum TabletLandscape: CGFloat, CaseIterable {
    /// BottomSafeAreaInset - 21.0
    /// Android: systemBars
    /// Category: tabletLandscape
    case bottomSafeAreaInset = 21.0
    /// HSafeAreaInset - 24.0
    /// iOS safeAreaInsets  / Android WindowInsetPadding. OBS Margin value 24pt transform into a "safe area inset" token, but beware this is not a safe area applied by device, is our margin transformed so that we can get reference values in Landscape, as Portrait device safe area are 0.
    /// Category: tabletLandscape
    case hSafeAreaInset = 24.0
    /// MaxcodeBlockwidth - 150.0
    /// Category: tabletLandscape
    case maxcodeBlockwidth = 150.0
    /// MaxColumnWidth - 260.0
    /// Category: tabletLandscape
    case maxColumnWidth = 260.0
    /// MaxImWideWidth - 450.0
    /// The maximum width we allow "full-width" images to grow to when the screen size increases, for example in landscape and on iPad
    /// Category: tabletLandscape
    case maxImWideWidth = 450.0
    /// MinColumnWidth - 280.0
    /// Category: tabletLandscape
    case minColumnWidth = 280.0
    /// TopNavBarHeaderLarge - 16.0
    /// Category: tabletLandscape
    case topNavBarHeaderLarge = 16.0
    /// TopNavBarHeaderSmall - 8.0
    /// Category: tabletLandscape
    case topNavBarHeaderSmall = 8.0

    /// Returns the numeric value of the token.
    public var value: CGFloat { rawValue }
}



