// Generated by umain-design-tokens-pipeline
// Do not edit this file manually

import SwiftUI
import Foundation
#if canImport(UIKit)
import UIKit
#endif
#if canImport(AppKit)
import AppKit
#endif

// MARK: - ElevationStyle

/**
 * Represents shadow/elevation properties for a single theme.
 * 
 * Usage:
 * ```swift
 * let style = EffectsElevation.borderedDefault.theme.light
 * // style.color - shadow color
 * // style.blur - blur radius in points
 * // style.positionY - vertical offset (positive = down)
 * // style.spread - shadow spread (optional)
 * ```
 */
public struct ElevationStyle {
    /// Shadow color with opacity
    public let color: Color
    /// Blur radius in points (0 = no blur)
    public let blur: CGFloat
    /// Vertical offset in points (positive = shadow below, negative = shadow above)
    public let positionY: CGFloat?
    /// Shadow spread in points (optional, expands/contracts shadow)
    public let spread: CGFloat?
}

// MARK: - ElevationTheme

/**
 * Contains elevation styles for both light and dark themes.
 * 
 * Usage:
 * ```swift
 * let theme = EffectsElevation.borderedDefault.theme
 * let lightStyle = theme.light
 * let darkStyle = theme.dark
 * 
 * // Get style for current color scheme
 * @Environment(\.colorScheme) var colorScheme
 * let style = theme.style(for: colorScheme)
 * ```
 */
public struct ElevationTheme {
    /// Elevation style for light mode
    public let light: ElevationStyle
    /// Elevation style for dark mode
    public let dark: ElevationStyle
    
    /// Get style for the specified color scheme
    /// - Parameter colorScheme: The color scheme (`.light` or `.dark`)
    /// - Returns: The appropriate elevation style for the color scheme
    public func style(for colorScheme: ColorScheme) -> ElevationStyle {
        switch colorScheme {
        case .light:
            return light
        case .dark:
            return dark
        @unknown default:
            return light
        }
    }
}

// MARK: - EffectsElevation

/**
 * Design system elevation tokens.
 * 
 * Each case represents a specific elevation style used throughout the app.
 * 
 * Usage Examples:
 * 
 * **Basic usage with ViewModifier:**
 * ```swift
 * Button("Press Me") {}
 *     .elevation(.borderedDefault)
 * ```
 * 
 * **Manual shadow application:**
 * ```swift
 * @Environment(\.colorScheme) var colorScheme
 * let style = EffectsElevation.raised.theme.style(for: colorScheme)
 * 
 * RoundedRectangle(cornerRadius: 8)
 *     .shadow(
 *         color: style.color,
 *         radius: style.blur,
 *         x: 0,
 *         y: style.positionY ?? 0
 *     )
 * ```
 * 
 * **Accessing specific theme:**
 * ```swift
 * let lightStyle = EffectsElevation.borderedDefault.theme.light
 * let darkStyle = EffectsElevation.borderedDefault.theme.dark
 * ```
 */
public enum EffectsElevation: CaseIterable {
    case borderDefault
    case borderPressed
    case navigationBarOnScroll
    case raised
    case tabs
}

// MARK: - Elevation Data

private let elevationData: [EffectsElevation: ElevationTheme] = [
    .borderDefault: .init(
        light: .init(
            color: Color(hex: "#0000003D"),
            blur: 4.0,
            positionY: 2.0,
            spread: 1.0
        ),
        dark: .init(
            color: Color.clear,
            blur: 0.0,
            positionY: 0.0,
            spread: nil
        )
    ),
    .borderPressed: .init(
        light: .init(
            color: Color(hex: "#00000047"),
            blur: 2.0,
            positionY: 1.0,
            spread: 1.0
        ),
        dark: .init(
            color: Color.clear,
            blur: 0.0,
            positionY: 0.0,
            spread: nil
        )
    ),
    .navigationBarOnScroll: .init(
        light: .init(
            color: Color(hex: "#2F1FAA"),
            blur: 0.0,
            positionY: 1.0,
            spread: nil
        ),
        dark: .init(
            color: Color.clear,
            blur: 0.0,
            positionY: 0.0,
            spread: nil
        )
    ),
    .raised: .init(
        light: .init(
            color: Color(hex: "#00000026"),
            blur: 8.0,
            positionY: nil,
            spread: nil
        ),
        dark: .init(
            color: Color.clear,
            blur: 0.0,
            positionY: 0.0,
            spread: nil
        )
    ),
    .tabs: .init(
        light: .init(
            color: Color(hex: "#0000001A"),
            blur: 2.0,
            positionY: 1.0,
            spread: nil
        ),
        dark: .init(
            color: Color.clear,
            blur: 0.0,
            positionY: 0.0,
            spread: nil
        )
    ),
]

// MARK: - EffectsElevation Extension

extension EffectsElevation {
    /// Get the elevation theme (contains both light and dark styles)
    public var theme: ElevationTheme {
        elevationData[self]!
    }
}

// MARK: - ElevationModifier

/**
 * ViewModifier that applies elevation shadow to a view.
 * 
 * Automatically adapts to the current color scheme.
 * Matches Figma shadows pixel-perfectly by:
 * - Dividing blur radius by 2 (SwiftUI uses different shadow algorithm)
 * - Simulating spread with an additional shadow layer when spread > 0
 * 
 * Usage:
 * ```swift
 * Text("Hello")
 *     .modifier(ElevationModifier(elevation: .borderedDefault))
 * 
 * // Or use the convenience extension:
 * Text("Hello")
 *     .elevation(.borderedDefault)
 * ```
 */
struct ElevationModifier: ViewModifier {
    let elevation: EffectsElevation
    @Environment(\.colorScheme) var colorScheme
    
    func body(content: Content) -> some View {
        let style = elevation.theme.style(for: colorScheme)
        let offsetY = style.positionY ?? 0
        let spread = style.spread ?? 0
        
        return content
            .shadow(
                color: style.color,
                radius: style.blur / 2,
                x: 0,
                y: offsetY
            )
            .modifier(SpreadShadow(spread: spread, color: style.color))
    }
}

struct SpreadShadow: ViewModifier {
    let spread: CGFloat
    let color: Color
    
    func body(content: Content) -> some View {
        content.shadow(
            color: color,
            radius: spread > 0 ? spread / 2 : 0,
            x: 0,
            y: 0
        )
    }
}

// MARK: - View Extension

/**
 * Convenience extension to apply elevation shadows to any view.
 * 
 * Usage:
 * ```swift
 * // Apply to any view
 * RoundedRectangle(cornerRadius: 12)
 *     .fill(Color.background)
 *     .elevation(.raised)
 * 
 * // Apply to buttons
 * Button("Submit") {}
 *     .buttonStyle(.borderedProminent)
 *     .elevation(.borderedDefault)
 * 
 * // Apply to cards
 * VStack {
 *     Text("Card Content")
 * }
 * .padding()
 * .background(Color.cardBackground)
 * .cornerRadius(8)
 * .elevation(.borderedDefault)
 * ```
 */
@available(iOS 17.0, *)
extension View {
    /// Apply an elevation shadow to the view.
    /// - Parameter elevation: The elevation style to apply
    /// - Returns: A view with the elevation shadow applied
    public func elevation(_ elevation: EffectsElevation) -> some View {
        modifier(ElevationModifier(elevation: elevation))
    }
}
// MARK: - UIKit Helpers

/**
 * UIKit helper functions for applying elevation shadows.
 * 
 * Usage:
 * ```swift
 * let view = UIView()
 * let style = EffectsElevation.raised.theme.light
 * 
 * // Apply shadow to layer
 * view.layer.applyElevation(style)
 * 
 * // Or use the convenience method
 * view.applyElevation(.raised, colorScheme: .light)
 * ```
 */
#if canImport(UIKit)
extension CALayer {
    /// Apply elevation shadow properties to the layer.
    /// Matches Figma shadows by dividing blur by 2 and simulating spread.
    /// - Parameter style: The elevation style to apply
    public func applyElevation(_ style: ElevationStyle) {
        shadowColor = UIColor(style.color).cgColor
        shadowOpacity = 1.0
        shadowOffset = CGSize(width: 0, height: style.positionY ?? 0)
        shadowRadius = style.blur / 2  // Divide by 2 to match Figma
        
        // Spread simulation in UIKit (adjust shadow path)
        if let spread = style.spread, spread > 0 {
            masksToBounds = false
            // Grow the shadow path to simulate spread
            let expandedBounds = bounds.insetBy(dx: -spread, dy: -spread)
            shadowPath = UIBezierPath(roundedRect: expandedBounds, cornerRadius: cornerRadius + spread).cgPath
        }
    }
}

extension UIView {
    /// Apply elevation shadow to the view's layer.
    /// - Parameters:
    ///   - elevation: The elevation style to apply
    ///   - colorScheme: The color scheme to use (defaults to current trait collection)
    public func applyElevation(_ elevation: EffectsElevation, colorScheme: ColorScheme? = nil) {
        let scheme = colorScheme ?? (traitCollection.userInterfaceStyle == .dark ? .dark : .light)
        let style = elevation.theme.style(for: scheme)
        layer.applyElevation(style)
    }
}
#endif // canImport(UIKit)
