// Generated by umain-design-tokens-pipeline
// Do not edit this file manually

import SwiftUI
import Foundation
#if canImport(UIKit)
import UIKit
#endif
#if canImport(AppKit)
import AppKit
#endif

// MARK: - Gradientstops

/// Adaptive colors that switch between light and dark values.
/// Usage: Gradientstops.someToken
public enum Gradientstops: String, CaseIterable {
    /// FadeprimarybgStop01 - Light: #F8F8F800, Dark: #26262600
    /// Category: fade-primary-bg
    case FadeprimarybgStop01 = "FadeprimarybgStop01"
    /// FadesecondarybgStop01 - Light: #FFFFFF00, Dark: #18181800
    /// Category: fade-secondary-bg
    case FadesecondarybgStop01 = "FadesecondarybgStop01"
    /// FadeprimarybgStop02 - Light: #F8F8F8, Dark: #262626
    /// Category: fade-primary-bg
    case FadeprimarybgStop02 = "FadeprimarybgStop02"
    /// FadesecondarybgStop02 - Light: #FFFFFF, Dark: #181818
    /// Category: fade-secondary-bg
    case FadesecondarybgStop02 = "FadesecondarybgStop02"
}

#if os(iOS)
public extension UIColor {
    static func semantic(_ token: Gradientstops) -> UIColor {
        UIColor { trait in
            let isDark = (trait.userInterfaceStyle == .dark)
            switch token {
            case .FadeprimarybgStop01:
                return isDark ? UIColor(hex: "#26262600") : UIColor(hex: "#F8F8F800")
            case .FadesecondarybgStop01:
                return isDark ? UIColor(hex: "#18181800") : UIColor(hex: "#FFFFFF00")
            case .FadeprimarybgStop02:
                return isDark ? UIColor(hex: "#262626") : UIColor(hex: "#F8F8F8")
            case .FadesecondarybgStop02:
                return isDark ? UIColor(hex: "#181818") : UIColor(hex: "#FFFFFF")
            }
        }
    }
}
#endif // os(iOS)

#if os(iOS)
@available(iOS 17.0, *)
public extension Color {
    /// Returns a dynamic color that automatically adapts to light/dark mode.
    /// Uses UIColor trait provider under the hood, so it updates instantly when appearance changes.
    /// No need to pass `colorScheme` or use `@Environment` — just call `Color.semantic(.token)`.
    static func semantic(_ token: Gradientstops) -> Color {
        Color(UIColor.semantic(token))
    }
}
#endif // os(iOS)

