// Generated by umain-design-tokens-pipeline
// Do not edit this file manually

import SwiftUI
import Foundation
#if canImport(UIKit)
import UIKit
#endif
#if canImport(AppKit)
import AppKit
#endif

// MARK: - IconSize

/// IconSize tokens.
/// Usage: `IconSize.l.value`
public enum IconSize: CGFloat, CaseIterable {
    /// L - 28.0
    case l = 28.0
    /// M - 20.0
    case m = 20.0
    /// S - 18.0
    case s = 18.0
    /// Xs - 14.0
    case xs = 14.0
    /// Xxs - 10.0
    case xxs = 10.0

    /// Returns the numeric value of the token.
    public var value: CGFloat { rawValue }

    /// Returns a `CGSize` with square dimensions equal to the token value.
    public var size: CGSize { CGSize(width: rawValue, height: rawValue) }

    #if canImport(UIKit)
    /// Convenience for UIKit: returns a configured `UIImage.SymbolConfiguration`.
    public var symbolConfiguration: UIImage.SymbolConfiguration {
        UIImage.SymbolConfiguration(pointSize: rawValue)
    }
    #endif // canImport(UIKit)
}

