// Generated by umain-design-tokens-pipeline
// Do not edit this file manually

import SwiftUI
import Foundation
#if canImport(UIKit)
import UIKit
#endif
#if canImport(AppKit)
import AppKit
#endif

// MARK: - ImageSize

/// ImageSize tokens.
/// Usage: `ImageSize.l.value`
public enum ImageSize: CGFloat, CaseIterable {
    /// L - 136.0
    case l = 136.0
    /// M - 112.0
    case m = 112.0
    /// S - 80.0
    case s = 80.0
    /// Xl - 200.0
    case xl = 200.0
    /// Xs - 64.0
    case xs = 64.0
    /// Xxl - 320.0
    case xxl = 320.0
    /// Xxs - 40.0
    case xxs = 40.0

    /// Returns the numeric value of the token.
    public var value: CGFloat { rawValue }

    /// Returns a `CGSize` with square dimensions equal to the token value.
    public var size: CGSize { CGSize(width: rawValue, height: rawValue) }
}

