// Generated by umain-design-tokens-pipeline
// Do not edit this file manually

import SwiftUI
import Foundation
#if canImport(UIKit)
import UIKit
#endif
#if canImport(AppKit)
import AppKit
#endif

// MARK: - ImageSize

/// ImageSize tokens.
/// Usage: `ImageSize.l.value`
public enum ImageSize: CGFloat, CaseIterable {
    /// L - 152.0
    case l = 152.0
    /// M - 128.0
    case m = 128.0
    /// S - 96.0
    case s = 96.0
    /// Xl - 240.0
    case xl = 240.0
    /// Xs - 72.0
    case xs = 72.0
    /// Xxl - 375.0
    case xxl = 375.0
    /// Xxs - 44.0
    case xxs = 44.0

    /// Returns the numeric value of the token.
    public var value: CGFloat { rawValue }

    /// Returns a `CGSize` with square dimensions equal to the token value.
    public var size: CGSize { CGSize(width: rawValue, height: rawValue) }
}

