// Generated by umain-design-tokens-pipeline
// Do not edit this file manually

import SwiftUI
import Foundation
#if canImport(UIKit)
import UIKit
#endif
#if canImport(AppKit)
import AppKit
#endif


// MARK: - Color Extensions

extension Color {
    init(hex: String) {
        let hex = hex.trimmingCharacters(in: CharacterSet.alphanumerics.inverted)
        var int: UInt64 = 0
        Scanner(string: hex).scanHexInt64(&int)
        
        let r, g, b, a: UInt64
        switch hex.count {
        case 3:
            (r, g, b, a) = ((int >> 8) * 17, (int >> 4 & 0xF) * 17, (int & 0xF) * 17, 255)
        case 4:
            (r, g, b, a) = ((int >> 12) * 17, (int >> 8 & 0xF) * 17, (int >> 4 & 0xF) * 17, (int & 0xF) * 17)
        case 6:
            (r, g, b, a) = (int >> 16 & 0xFF, int >> 8 & 0xFF, int & 0xFF, 255)
        case 8:
            (r, g, b, a) = (int >> 24 & 0xFF, int >> 16 & 0xFF, int >> 8 & 0xFF, int & 0xFF)
        default:
            (r, g, b, a) = (0, 0, 0, 0)
        }
        
        self.init(.sRGB, red: Double(r) / 255, green: Double(g) / 255, blue: Double(b) / 255, opacity: Double(a) / 255)
    }
}

#if canImport(UIKit)
extension UIColor {
    convenience init(hex: String) {
        let hex = hex.trimmingCharacters(in: CharacterSet.alphanumerics.inverted)
        var int: UInt64 = 0
        Scanner(string: hex).scanHexInt64(&int)
        
        let r, g, b, a: UInt64
        switch hex.count {
        case 3:
            (r, g, b, a) = ((int >> 8) * 17, (int >> 4 & 0xF) * 17, (int & 0xF) * 17, 255)
        case 4:
            (r, g, b, a) = ((int >> 12) * 17, (int >> 8 & 0xF) * 17, (int >> 4 & 0xF) * 17, (int & 0xF) * 17)
        case 6:
            (r, g, b, a) = (int >> 16 & 0xFF, int >> 8 & 0xFF, int & 0xFF, 255)
        case 8:
            (r, g, b, a) = (int >> 24 & 0xFF, int >> 16 & 0xFF, int >> 8 & 0xFF, int & 0xFF)
        default:
            (r, g, b, a) = (0, 0, 0, 0)
        }
        
        self.init(red: CGFloat(r) / 255, green: CGFloat(g) / 255, blue: CGFloat(b) / 255, alpha: CGFloat(a) / 255)
    }
}
#endif

// MARK: - Palette

/// Palette tokens.
/// Usage: Palette.someToken.value
public enum Palette: CaseIterable {
    /// Gold100 - #FCE8B0
    /// Category: Value/UI Palette/Gold
    case gold100
    /// Green100 - #F2F6F3
    /// Category: Value/UI Palette/Green
    case green100
    /// Greyscale100 - #F8F8F8
    /// Category: Value/UI Palette/Greyscale
    case greyscale100
    /// Orange100 - #FFF8F3
    /// Category: Value/UI Palette/Orange
    case orange100
    /// Red100 - #FEF3F3
    /// Category: Value/UI Palette/Red
    case red100
    /// Greyscale10000 - #F8F8F800
    /// Category: Value/UI Palette/Greyscale
    case greyscale10000
    /// Greyscale200 - #F2F2F2
    /// Category: Value/UI Palette/Greyscale
    case greyscale200
    /// Blue300 - #3DB5FF
    /// Category: Value/UI Palette/Blue
    case blue300
    /// Fuchsia300 - #FF7DB8
    /// Category: Value/UI Palette/Fuchsia
    case fuchsia300
    /// Greyscale300 - #D4D4D4
    /// Category: Value/UI Palette/Greyscale
    case greyscale300
    /// Gold400 - #FFAA00
    /// Category: Value/UI Palette/Gold
    case gold400
    /// Green400 - #4DAE6E
    /// Category: Value/UI Palette/Green
    case green400
    /// Greyscale400 - #ABABAB
    /// Category: Value/UI Palette/Greyscale
    case greyscale400
    /// Orange400 - #ED7F42
    /// Category: Value/UI Palette/Orange
    case orange400
    /// Red400 - #FC5C62
    /// Category: Value/UI Palette/Red
    case red400
    /// Green40030 - #4DAE6E4D
    /// Category: Value/UI Palette/Green
    case green40030
    /// Orange40030 - #ED7F424D
    /// Category: Value/UI Palette/Orange
    case orange40030
    /// Red40030 - #FC5C624D
    /// Category: Value/UI Palette/Red
    case red40030
    /// Greyscale500 - #939393
    /// Category: Value/UI Palette/Greyscale
    case greyscale500
    /// Greyscale600 - #6D6D6D
    /// Category: Value/UI Palette/Greyscale
    case greyscale600
    /// Blue700 - #005FA3
    /// Category: Value/UI Palette/Blue
    case blue700
    /// Fuchsia700 - #920847
    /// Category: Value/UI Palette/Fuchsia
    case fuchsia700
    /// Gold700 - #B08000
    /// Category: Value/UI Palette/Gold
    case gold700
    /// Green700 - #224830
    /// Category: Value/UI Palette/Green
    case green700
    /// Greyscale700 - #3A3A3A
    /// Category: Value/UI Palette/Greyscale
    case greyscale700
    /// Orange700 - #B24C00
    /// Category: Value/UI Palette/Orange
    case orange700
    /// Red700 - #CC0008
    /// Category: Value/UI Palette/Red
    case red700
    /// Greyscale800 - #262626
    /// Category: Value/UI Palette/Greyscale
    case greyscale800
    /// Greyscale80000 - #26262600
    /// Category: Value/UI Palette/Greyscale
    case greyscale80000
    /// Greyscale80015 - #26262626
    /// Category: Value/UI Palette/Greyscale
    case greyscale80015
    /// Greyscale80020 - #26262633
    /// Category: Value/UI Palette/Greyscale
    case greyscale80020
    /// Greyscale900 - #181818
    /// Category: Value/UI Palette/Greyscale
    case greyscale900
    /// Greyscale90000 - #18181800
    /// Category: Value/UI Palette/Greyscale
    case greyscale90000
    /// White - #FFFFFF
    /// Category: Value/UI Palette/Greyscale
    case white
    /// White00 - #FFFFFF00
    /// Category: Value/UI Palette/Greyscale
    case white00
    /// White15 - #FFFFFF26
    /// Category: Value/UI Palette/Greyscale
    case white15
    /// White20 - #FFFFFF33
    /// Category: Value/UI Palette/Greyscale
    case white20

    public var value: Color {
        switch self {
        case .gold100:
            return Color(hex: "#FCE8B0")
        case .green100:
            return Color(hex: "#F2F6F3")
        case .greyscale100:
            return Color(hex: "#F8F8F8")
        case .orange100:
            return Color(hex: "#FFF8F3")
        case .red100:
            return Color(hex: "#FEF3F3")
        case .greyscale10000:
            return Color(hex: "#F8F8F800")
        case .greyscale200:
            return Color(hex: "#F2F2F2")
        case .blue300:
            return Color(hex: "#3DB5FF")
        case .fuchsia300:
            return Color(hex: "#FF7DB8")
        case .greyscale300:
            return Color(hex: "#D4D4D4")
        case .gold400:
            return Color(hex: "#FFAA00")
        case .green400:
            return Color(hex: "#4DAE6E")
        case .greyscale400:
            return Color(hex: "#ABABAB")
        case .orange400:
            return Color(hex: "#ED7F42")
        case .red400:
            return Color(hex: "#FC5C62")
        case .green40030:
            return Color(hex: "#4DAE6E4D")
        case .orange40030:
            return Color(hex: "#ED7F424D")
        case .red40030:
            return Color(hex: "#FC5C624D")
        case .greyscale500:
            return Color(hex: "#939393")
        case .greyscale600:
            return Color(hex: "#6D6D6D")
        case .blue700:
            return Color(hex: "#005FA3")
        case .fuchsia700:
            return Color(hex: "#920847")
        case .gold700:
            return Color(hex: "#B08000")
        case .green700:
            return Color(hex: "#224830")
        case .greyscale700:
            return Color(hex: "#3A3A3A")
        case .orange700:
            return Color(hex: "#B24C00")
        case .red700:
            return Color(hex: "#CC0008")
        case .greyscale800:
            return Color(hex: "#262626")
        case .greyscale80000:
            return Color(hex: "#26262600")
        case .greyscale80015:
            return Color(hex: "#26262626")
        case .greyscale80020:
            return Color(hex: "#26262633")
        case .greyscale900:
            return Color(hex: "#181818")
        case .greyscale90000:
            return Color(hex: "#18181800")
        case .white:
            return Color(hex: "#FFFFFF")
        case .white00:
            return Color(hex: "#FFFFFF00")
        case .white15:
            return Color(hex: "#FFFFFF26")
        case .white20:
            return Color(hex: "#FFFFFF33")
        }
    }
}

/// Palette color category for grouping in UI (matches Figma UI Palette).
public enum PaletteColorCategory: String, CaseIterable {
    case greyscale
    case gold
    case red
    case green
    case orange
    case blue
    case fuchsia
    case other
}

public extension Palette {
    /// Category for showcase grouping (matches Figma).
    var category: PaletteColorCategory {
        switch self {
        case .gold100: return .gold
        case .green100: return .green
        case .greyscale100: return .greyscale
        case .orange100: return .orange
        case .red100: return .red
        case .greyscale10000: return .greyscale
        case .greyscale200: return .greyscale
        case .blue300: return .blue
        case .fuchsia300: return .fuchsia
        case .greyscale300: return .greyscale
        case .gold400: return .gold
        case .green400: return .green
        case .greyscale400: return .greyscale
        case .orange400: return .orange
        case .red400: return .red
        case .green40030: return .green
        case .orange40030: return .orange
        case .red40030: return .red
        case .greyscale500: return .greyscale
        case .greyscale600: return .greyscale
        case .blue700: return .blue
        case .fuchsia700: return .fuchsia
        case .gold700: return .gold
        case .green700: return .green
        case .greyscale700: return .greyscale
        case .orange700: return .orange
        case .red700: return .red
        case .greyscale800: return .greyscale
        case .greyscale80000: return .greyscale
        case .greyscale80015: return .greyscale
        case .greyscale80020: return .greyscale
        case .greyscale900: return .greyscale
        case .greyscale90000: return .greyscale
        case .white: return .greyscale
        case .white00: return .greyscale
        case .white15: return .greyscale
        case .white20: return .greyscale
        }
    }
}

