// Generated by umain-design-tokens-pipeline
// Do not edit this file manually

import SwiftUI
import Foundation
#if canImport(UIKit)
import UIKit
#endif
#if canImport(AppKit)
import AppKit
#endif


// MARK: - Color Extensions

extension Color {
    init(hex: String) {
        let hex = hex.trimmingCharacters(in: CharacterSet.alphanumerics.inverted)
        var int: UInt64 = 0
        Scanner(string: hex).scanHexInt64(&int)
        
        let r, g, b, a: UInt64
        switch hex.count {
        case 3:
            (r, g, b, a) = ((int >> 8) * 17, (int >> 4 & 0xF) * 17, (int & 0xF) * 17, 255)
        case 4:
            (r, g, b, a) = ((int >> 12) * 17, (int >> 8 & 0xF) * 17, (int >> 4 & 0xF) * 17, (int & 0xF) * 17)
        case 6:
            (r, g, b, a) = (int >> 16 & 0xFF, int >> 8 & 0xFF, int & 0xFF, 255)
        case 8:
            (r, g, b, a) = (int >> 24 & 0xFF, int >> 16 & 0xFF, int >> 8 & 0xFF, int & 0xFF)
        default:
            (r, g, b, a) = (0, 0, 0, 0)
        }
        
        self.init(.sRGB, red: Double(r) / 255, green: Double(g) / 255, blue: Double(b) / 255, opacity: Double(a) / 255)
    }
}

#if canImport(UIKit)
extension UIColor {
    convenience init(hex: String) {
        let hex = hex.trimmingCharacters(in: CharacterSet.alphanumerics.inverted)
        var int: UInt64 = 0
        Scanner(string: hex).scanHexInt64(&int)
        
        let r, g, b, a: UInt64
        switch hex.count {
        case 3:
            (r, g, b, a) = ((int >> 8) * 17, (int >> 4 & 0xF) * 17, (int & 0xF) * 17, 255)
        case 4:
            (r, g, b, a) = ((int >> 12) * 17, (int >> 8 & 0xF) * 17, (int >> 4 & 0xF) * 17, (int & 0xF) * 17)
        case 6:
            (r, g, b, a) = (int >> 16 & 0xFF, int >> 8 & 0xFF, int & 0xFF, 255)
        case 8:
            (r, g, b, a) = (int >> 24 & 0xFF, int >> 16 & 0xFF, int >> 8 & 0xFF, int & 0xFF)
        default:
            (r, g, b, a) = (0, 0, 0, 0)
        }
        
        self.init(red: CGFloat(r) / 255, green: CGFloat(g) / 255, blue: CGFloat(b) / 255, alpha: CGFloat(a) / 255)
    }
}
#endif

// MARK: - Palette

/// Palette tokens.
/// Usage: Palette.someToken.value
public enum Palette: CaseIterable {
    /// Gold100 - #FBE4A7
    /// Category: Value/UI Palette/Gold
    case gold100
    /// Green100 - #F4F7F5
    /// Category: Value/UI Palette/Green
    case green100
    /// Greyscale100 - #F9F9F9
    /// Category: Value/UI Palette/Greyscale
    case greyscale100
    /// Orange100 - #FFF9F5
    /// Category: Value/UI Palette/Orange
    case orange100
    /// Red100 - #FDF2F2
    /// Category: Value/UI Palette/Red
    case red100
    /// Greyscale10000 - #F9F9F900
    /// Category: Value/UI Palette/Greyscale
    case greyscale10000
    /// Greyscale200 - #F3F3F3
    /// Category: Value/UI Palette/Greyscale
    case greyscale200
    /// Blue300 - #4DBBFF
    /// Category: Value/UI Palette/Blue
    case blue300
    /// Fuchsia300 - #FF8FC3
    /// Category: Value/UI Palette/Fuchsia
    case fuchsia300
    /// Greyscale300 - #D6D6D6
    /// Category: Value/UI Palette/Greyscale
    case greyscale300
    /// Gold400 - #FFBC0D
    /// Category: Value/UI Palette/Gold
    case gold400
    /// Green400 - #54B077
    /// Category: Value/UI Palette/Green
    case green400
    /// Greyscale400 - #ADADAD
    /// Category: Value/UI Palette/Greyscale
    case greyscale400
    /// Orange400 - #EF8849
    /// Category: Value/UI Palette/Orange
    case orange400
    /// Red400 - #FD686D
    /// Category: Value/UI Palette/Red
    case red400
    /// Green40030 - #54B0774D
    /// Category: Value/UI Palette/Green
    case green40030
    /// Orange40030 - #EF88494D
    /// Category: Value/UI Palette/Orange
    case orange40030
    /// Red40030 - #FD686D4D
    /// Category: Value/UI Palette/Red
    case red40030
    /// Greyscale500 - #959595
    /// Category: Value/UI Palette/Greyscale
    case greyscale500
    /// Greyscale600 - #6F6F6F
    /// Category: Value/UI Palette/Greyscale
    case greyscale600
    /// Blue700 - #006BAE
    /// Category: Value/UI Palette/Blue
    case blue700
    /// Fuchsia700 - #9A0A4D
    /// Category: Value/UI Palette/Fuchsia
    case fuchsia700
    /// Gold700 - #C08B00
    /// Category: Value/UI Palette/Gold
    case gold700
    /// Green700 - #264F36
    /// Category: Value/UI Palette/Green
    case green700
    /// Greyscale700 - #3D3D3D
    /// Category: Value/UI Palette/Greyscale
    case greyscale700
    /// Orange700 - #BE5100
    /// Category: Value/UI Palette/Orange
    case orange700
    /// Red700 - #DB0007
    /// Category: Value/UI Palette/Red
    case red700
    /// Greyscale800 - #292929
    /// Category: Value/UI Palette/Greyscale
    case greyscale800
    /// Greyscale80000 - #29292900
    /// Category: Value/UI Palette/Greyscale
    case greyscale80000
    /// Greyscale80015 - #29292926
    /// Category: Value/UI Palette/Greyscale
    case greyscale80015
    /// Greyscale80020 - #29292933
    /// Category: Value/UI Palette/Greyscale
    case greyscale80020
    /// Greyscale900 - #1B1B1B
    /// Category: Value/UI Palette/Greyscale
    case greyscale900
    /// Greyscale90000 - #1B1B1B00
    /// Category: Value/UI Palette/Greyscale
    case greyscale90000
    /// White - #FFFFFF
    /// Category: Value/UI Palette/Greyscale
    case white
    /// White00 - #FFFFFF00
    /// Category: Value/UI Palette/Greyscale
    case white00
    /// White15 - #FFFFFF26
    /// Category: Value/UI Palette/Greyscale
    case white15
    /// White20 - #FFFFFF33
    /// Category: Value/UI Palette/Greyscale
    case white20

    public var value: Color {
        switch self {
        case .gold100:
            return Color(hex: "#FBE4A7")
        case .green100:
            return Color(hex: "#F4F7F5")
        case .greyscale100:
            return Color(hex: "#F9F9F9")
        case .orange100:
            return Color(hex: "#FFF9F5")
        case .red100:
            return Color(hex: "#FDF2F2")
        case .greyscale10000:
            return Color(hex: "#F9F9F900")
        case .greyscale200:
            return Color(hex: "#F3F3F3")
        case .blue300:
            return Color(hex: "#4DBBFF")
        case .fuchsia300:
            return Color(hex: "#FF8FC3")
        case .greyscale300:
            return Color(hex: "#D6D6D6")
        case .gold400:
            return Color(hex: "#FFBC0D")
        case .green400:
            return Color(hex: "#54B077")
        case .greyscale400:
            return Color(hex: "#ADADAD")
        case .orange400:
            return Color(hex: "#EF8849")
        case .red400:
            return Color(hex: "#FD686D")
        case .green40030:
            return Color(hex: "#54B0774D")
        case .orange40030:
            return Color(hex: "#EF88494D")
        case .red40030:
            return Color(hex: "#FD686D4D")
        case .greyscale500:
            return Color(hex: "#959595")
        case .greyscale600:
            return Color(hex: "#6F6F6F")
        case .blue700:
            return Color(hex: "#006BAE")
        case .fuchsia700:
            return Color(hex: "#9A0A4D")
        case .gold700:
            return Color(hex: "#C08B00")
        case .green700:
            return Color(hex: "#264F36")
        case .greyscale700:
            return Color(hex: "#3D3D3D")
        case .orange700:
            return Color(hex: "#BE5100")
        case .red700:
            return Color(hex: "#DB0007")
        case .greyscale800:
            return Color(hex: "#292929")
        case .greyscale80000:
            return Color(hex: "#29292900")
        case .greyscale80015:
            return Color(hex: "#29292926")
        case .greyscale80020:
            return Color(hex: "#29292933")
        case .greyscale900:
            return Color(hex: "#1B1B1B")
        case .greyscale90000:
            return Color(hex: "#1B1B1B00")
        case .white:
            return Color(hex: "#FFFFFF")
        case .white00:
            return Color(hex: "#FFFFFF00")
        case .white15:
            return Color(hex: "#FFFFFF26")
        case .white20:
            return Color(hex: "#FFFFFF33")
        }
    }
}

/// Palette color category for grouping in UI (matches Figma UI Palette).
public enum PaletteColorCategory: String, CaseIterable {
    case greyscale
    case gold
    case red
    case green
    case orange
    case blue
    case fuchsia
    case other
}

public extension Palette {
    /// Category for showcase grouping (matches Figma).
    var category: PaletteColorCategory {
        switch self {
        case .gold100: return .gold
        case .green100: return .green
        case .greyscale100: return .greyscale
        case .orange100: return .orange
        case .red100: return .red
        case .greyscale10000: return .greyscale
        case .greyscale200: return .greyscale
        case .blue300: return .blue
        case .fuchsia300: return .fuchsia
        case .greyscale300: return .greyscale
        case .gold400: return .gold
        case .green400: return .green
        case .greyscale400: return .greyscale
        case .orange400: return .orange
        case .red400: return .red
        case .green40030: return .green
        case .orange40030: return .orange
        case .red40030: return .red
        case .greyscale500: return .greyscale
        case .greyscale600: return .greyscale
        case .blue700: return .blue
        case .fuchsia700: return .fuchsia
        case .gold700: return .gold
        case .green700: return .green
        case .greyscale700: return .greyscale
        case .orange700: return .orange
        case .red700: return .red
        case .greyscale800: return .greyscale
        case .greyscale80000: return .greyscale
        case .greyscale80015: return .greyscale
        case .greyscale80020: return .greyscale
        case .greyscale900: return .greyscale
        case .greyscale90000: return .greyscale
        case .white: return .greyscale
        case .white00: return .greyscale
        case .white15: return .greyscale
        case .white20: return .greyscale
        }
    }
}

