// Generated by UmainDesignToken
// Do not edit this file manually

import SwiftUI
#if canImport(UIKit)
import UIKit
#endif

// MARK: - Primitives

/// Primitives tokens.
/// Usage: Primitives.someToken.value
public enum Primitives: CaseIterable {
    /// BigstoneNeutralsValue0 - #FFFFFF
    /// Category: Big Stone/color/neutrals
    case bigstoneNeutralsValue0
    /// PlumNeutralsValue0 - #FFFFFF
    /// Category: Plum/color/neutrals
    case plumNeutralsValue0
    /// BigstoneNeutralsValue10 - #E7E7E7
    /// Category: Big Stone/color/neutrals
    case bigstoneNeutralsValue10
    /// BigstonePrimaryValue10 - #E6F0F8
    /// Category: Big Stone/color/primary
    case bigstonePrimaryValue10
    /// BigstoneSecondaryValue10 - #DFF9E8
    /// Category: Big Stone/color/secondary
    case bigstoneSecondaryValue10
    /// PlumNeutralsValue10 - #E7E7E7
    /// Category: Plum/color/neutrals
    case plumNeutralsValue10
    /// PlumPrimaryValue10 - #F7EEF9
    /// Category: Plum/color/primary
    case plumPrimaryValue10
    /// PlumSecondaryValue10 - #DFF9E8
    /// Category: Plum/color/secondary
    case plumSecondaryValue10
    /// BigstoneNeutralsValue100 - #000000
    /// Category: Big Stone/color/neutrals
    case bigstoneNeutralsValue100
    /// PlumNeutralsValue100 - #000000
    /// Category: Plum/color/neutrals
    case plumNeutralsValue100
    /// BigstoneNeutralsValue20 - #D1D1D1
    /// Category: Big Stone/color/neutrals
    case bigstoneNeutralsValue20
    /// BigstonePrimaryValue20 - #C7E1F0
    /// Category: Big Stone/color/primary
    case bigstonePrimaryValue20
    /// BigstoneSecondaryValue20 - #C1F1D3
    /// Category: Big Stone/color/secondary
    case bigstoneSecondaryValue20
    /// PlumNeutralsValue20 - #D1D1D1
    /// Category: Plum/color/neutrals
    case plumNeutralsValue20
    /// PlumPrimaryValue20 - #EFDCF2
    /// Category: Plum/color/primary
    case plumPrimaryValue20
    /// PlumSecondaryValue20 - #C1F1D3
    /// Category: Plum/color/secondary
    case plumSecondaryValue20
    /// BigstoneNeutralsValue30 - #B0B0B0
    /// Category: Big Stone/color/neutrals
    case bigstoneNeutralsValue30
    /// BigstonePrimaryValue30 - #96C7E3
    /// Category: Big Stone/color/primary
    case bigstonePrimaryValue30
    /// BigstoneSecondaryValue30 - #91E4B0
    /// Category: Big Stone/color/secondary
    case bigstoneSecondaryValue30
    /// PlumNeutralsValue30 - #B0B0B0
    /// Category: Plum/color/neutrals
    case plumNeutralsValue30
    /// PlumPrimaryValue30 - #E2C0E7
    /// Category: Plum/color/primary
    case plumPrimaryValue30
    /// PlumSecondaryValue30 - #91E4B0
    /// Category: Plum/color/secondary
    case plumSecondaryValue30
    /// BigstoneNeutralsValue40 - #888888
    /// Category: Big Stone/color/neutrals
    case bigstoneNeutralsValue40
    /// BigstonePrimaryValue40 - #5EAAD2
    /// Category: Big Stone/color/primary
    case bigstonePrimaryValue40
    /// BigstoneSecondaryValue40 - #5ACE86
    /// Category: Big Stone/color/secondary
    case bigstoneSecondaryValue40
    /// PlumNeutralsValue40 - #888888
    /// Category: Plum/color/neutrals
    case plumNeutralsValue40
    /// PlumPrimaryValue40 - #D29AD8
    /// Category: Plum/color/primary
    case plumPrimaryValue40
    /// PlumSecondaryValue40 - #5ACE86
    /// Category: Plum/color/secondary
    case plumSecondaryValue40
    /// BigstonePrimaryValue5 - #F3F8FC
    /// Category: Big Stone/color/primary
    case bigstonePrimaryValue5
    /// BigstoneSecondaryValue5 - #F1FCF5
    /// Category: Big Stone/color/secondary
    case bigstoneSecondaryValue5
    /// PlumPrimaryValue5 - #FBF7FC
    /// Category: Plum/color/primary
    case plumPrimaryValue5
    /// PlumSecondaryValue5 - #F1FCF5
    /// Category: Plum/color/secondary
    case plumSecondaryValue5
    /// BigstoneNeutralsValue50 - #6D6D6D
    /// Category: Big Stone/color/neutrals
    case bigstoneNeutralsValue50
    /// BigstonePrimaryValue50 - #3A8FBD
    /// Category: Big Stone/color/primary
    case bigstonePrimaryValue50
    /// BigstoneSecondaryValue50 - #33B465
    /// Category: Big Stone/color/secondary
    case bigstoneSecondaryValue50
    /// PlumNeutralsValue50 - #6D6D6D
    /// Category: Plum/color/neutrals
    case plumNeutralsValue50
    /// PlumPrimaryValue50 - #BB71C4
    /// Category: Plum/color/primary
    case plumPrimaryValue50
    /// PlumSecondaryValue50 - #33B465
    /// Category: Plum/color/secondary
    case plumSecondaryValue50
    /// BigstoneNeutralsValue60 - #5D5D5D
    /// Category: Big Stone/color/neutrals
    case bigstoneNeutralsValue60
    /// BigstonePrimaryValue60 - #2973A0
    /// Category: Big Stone/color/primary
    case bigstonePrimaryValue60
    /// BigstoneSecondaryValue60 - #25944F
    /// Category: Big Stone/color/secondary
    case bigstoneSecondaryValue60
    /// PlumNeutralsValue60 - #5D5D5D
    /// Category: Plum/color/neutrals
    case plumNeutralsValue60
    /// PlumPrimaryValue60 - #A152A7
    /// Category: Plum/color/primary
    case plumPrimaryValue60
    /// PlumSecondaryValue60 - #25944F
    /// Category: Plum/color/secondary
    case plumSecondaryValue60
    /// BigstoneNeutralsValue70 - #4F4F4F
    /// Category: Big Stone/color/neutrals
    case bigstoneNeutralsValue70
    /// BigstonePrimaryValue70 - #235D81
    /// Category: Big Stone/color/primary
    case bigstonePrimaryValue70
    /// BigstoneSecondaryValue70 - #207541
    /// Category: Big Stone/color/secondary
    case bigstoneSecondaryValue70
    /// PlumNeutralsValue70 - #4F4F4F
    /// Category: Plum/color/neutrals
    case plumNeutralsValue70
    /// PlumPrimaryValue70 - #7E3E82
    /// Category: Plum/color/primary
    case plumPrimaryValue70
    /// PlumSecondaryValue70 - #207541
    /// Category: Plum/color/secondary
    case plumSecondaryValue70
    /// BigstoneNeutralsValue80 - #454545
    /// Category: Big Stone/color/neutrals
    case bigstoneNeutralsValue80
    /// BigstonePrimaryValue80 - #204E6C
    /// Category: Big Stone/color/primary
    case bigstonePrimaryValue80
    /// BigstoneSecondaryValue80 - #1E5D37
    /// Category: Big Stone/color/secondary
    case bigstoneSecondaryValue80
    /// PlumNeutralsValue80 - #454545
    /// Category: Plum/color/neutrals
    case plumNeutralsValue80
    /// PlumPrimaryValue80 - #6E3771
    /// Category: Plum/color/primary
    case plumPrimaryValue80
    /// PlumSecondaryValue80 - #1E5D37
    /// Category: Plum/color/secondary
    case plumSecondaryValue80
    /// BigstoneNeutralsValue90 - #3D3D3D
    /// Category: Big Stone/color/neutrals
    case bigstoneNeutralsValue90
    /// BigstonePrimaryValue90 - #20435A
    /// Category: Big Stone/color/primary
    case bigstonePrimaryValue90
    /// BigstoneSecondaryValue90 - #153C25
    /// Category: Big Stone/color/secondary
    case bigstoneSecondaryValue90
    /// PlumNeutralsValue90 - #3D3D3D
    /// Category: Plum/color/neutrals
    case plumNeutralsValue90
    /// PlumPrimaryValue90 - #5C315E
    /// Category: Plum/color/primary
    case plumPrimaryValue90
    /// PlumSecondaryValue90 - #153C25
    /// Category: Plum/color/secondary
    case plumSecondaryValue90
    /// BigstoneNeutralsValue95 - #181818
    /// Category: Big Stone/color/neutrals
    case bigstoneNeutralsValue95
    /// BigstonePrimaryValue95 - #152B3C
    /// Category: Big Stone/color/primary
    case bigstonePrimaryValue95
    /// BigstoneSecondaryValue95 - #092A17
    /// Category: Big Stone/color/secondary
    case bigstoneSecondaryValue95
    /// PlumNeutralsValue95 - #181818
    /// Category: Plum/color/neutrals
    case plumNeutralsValue95
    /// PlumPrimaryValue95 - #3A173B
    /// Category: Plum/color/primary
    case plumPrimaryValue95
    /// PlumSecondaryValue95 - #092A17
    /// Category: Plum/color/secondary
    case plumSecondaryValue95
    /// BigstoneRadiusRadiusl - 48.0
    /// Category: Big Stone/radius
    case bigstoneRadiusRadiusl
    /// PlumRadiusRadiusl - 48.0
    /// Category: Plum/radius
    case plumRadiusRadiusl
    /// BigstoneRadiusRadiusm - 16.0
    /// Category: Big Stone/radius
    case bigstoneRadiusRadiusm
    /// PlumRadiusRadiusm - 16.0
    /// Category: Plum/radius
    case plumRadiusRadiusm
    /// BigstoneRadiusRadiusround - 100.0
    /// Category: Big Stone/radius
    case bigstoneRadiusRadiusround
    /// PlumRadiusRadiusround - 100.0
    /// Category: Plum/radius
    case plumRadiusRadiusround
    /// BigstoneRadiusRadiuss - 8.0
    /// Category: Big Stone/radius
    case bigstoneRadiusRadiuss
    /// PlumRadiusRadiuss - 8.0
    /// Category: Plum/radius
    case plumRadiusRadiuss
    /// BigstoneRadiusRadiusxl - 64.0
    /// Category: Big Stone/radius
    case bigstoneRadiusRadiusxl
    /// PlumRadiusRadiusxl - 64.0
    /// Category: Plum/radius
    case plumRadiusRadiusxl
    /// BigstoneRadiusRadiusxs - 4.0
    /// Category: Big Stone/radius
    case bigstoneRadiusRadiusxs
    /// PlumRadiusRadiusxs - 4.0
    /// Category: Plum/radius
    case plumRadiusRadiusxs
    /// BigstoneSpacingSpacing01 - 4.0
    /// Category: Big Stone/spacing
    case bigstoneSpacingSpacing01
    /// PlumSpacingSpacing01 - 4.0
    /// Category: Plum/spacing
    case plumSpacingSpacing01
    /// BigstoneSpacingSpacing02 - 8.0
    /// Category: Big Stone/spacing
    case bigstoneSpacingSpacing02
    /// PlumSpacingSpacing02 - 8.0
    /// Category: Plum/spacing
    case plumSpacingSpacing02
    /// BigstoneSpacingSpacing03 - 16.0
    /// Category: Big Stone/spacing
    case bigstoneSpacingSpacing03
    /// PlumSpacingSpacing03 - 16.0
    /// Category: Plum/spacing
    case plumSpacingSpacing03
    /// BigstoneSpacingSpacing04 - 24.0
    /// Category: Big Stone/spacing
    case bigstoneSpacingSpacing04
    /// PlumSpacingSpacing04 - 24.0
    /// Category: Plum/spacing
    case plumSpacingSpacing04
    /// BigstoneSpacingSpacing05 - 32.0
    /// Category: Big Stone/spacing
    case bigstoneSpacingSpacing05
    /// PlumSpacingSpacing05 - 32.0
    /// Category: Plum/spacing
    case plumSpacingSpacing05
    /// BigstoneSpacingSpacing06 - 40.0
    /// Category: Big Stone/spacing
    case bigstoneSpacingSpacing06
    /// PlumSpacingSpacing06 - 40.0
    /// Category: Plum/spacing
    case plumSpacingSpacing06
    /// BigstoneSpacingSpacing07 - 48.0
    /// Category: Big Stone/spacing
    case bigstoneSpacingSpacing07
    /// PlumSpacingSpacing07 - 48.0
    /// Category: Plum/spacing
    case plumSpacingSpacing07
    /// BigstoneSpacingSpacing08 - 56.0
    /// Category: Big Stone/spacing
    case bigstoneSpacingSpacing08
    /// PlumSpacingSpacing08 - 56.0
    /// Category: Plum/spacing
    case plumSpacingSpacing08
    /// BigstoneSpacingSpacing09 - 64.0
    /// Category: Big Stone/spacing
    case bigstoneSpacingSpacing09
    /// PlumSpacingSpacing09 - 64.0
    /// Category: Plum/spacing
    case plumSpacingSpacing09
    /// BigstoneSpacingSpacing10 - 72.0
    /// Category: Big Stone/spacing
    case bigstoneSpacingSpacing10
    /// PlumSpacingSpacing10 - 72.0
    /// Category: Plum/spacing
    case plumSpacingSpacing10

    public var value: Color {
        switch self {
        case .bigstoneNeutralsValue0:
            return Color(hex: "#FFFFFF")
        case .plumNeutralsValue0:
            return Color(hex: "#FFFFFF")
        case .bigstoneNeutralsValue10:
            return Color(hex: "#E7E7E7")
        case .bigstonePrimaryValue10:
            return Color(hex: "#E6F0F8")
        case .bigstoneSecondaryValue10:
            return Color(hex: "#DFF9E8")
        case .plumNeutralsValue10:
            return Color(hex: "#E7E7E7")
        case .plumPrimaryValue10:
            return Color(hex: "#F7EEF9")
        case .plumSecondaryValue10:
            return Color(hex: "#DFF9E8")
        case .bigstoneNeutralsValue100:
            return Color(hex: "#000000")
        case .plumNeutralsValue100:
            return Color(hex: "#000000")
        case .bigstoneNeutralsValue20:
            return Color(hex: "#D1D1D1")
        case .bigstonePrimaryValue20:
            return Color(hex: "#C7E1F0")
        case .bigstoneSecondaryValue20:
            return Color(hex: "#C1F1D3")
        case .plumNeutralsValue20:
            return Color(hex: "#D1D1D1")
        case .plumPrimaryValue20:
            return Color(hex: "#EFDCF2")
        case .plumSecondaryValue20:
            return Color(hex: "#C1F1D3")
        case .bigstoneNeutralsValue30:
            return Color(hex: "#B0B0B0")
        case .bigstonePrimaryValue30:
            return Color(hex: "#96C7E3")
        case .bigstoneSecondaryValue30:
            return Color(hex: "#91E4B0")
        case .plumNeutralsValue30:
            return Color(hex: "#B0B0B0")
        case .plumPrimaryValue30:
            return Color(hex: "#E2C0E7")
        case .plumSecondaryValue30:
            return Color(hex: "#91E4B0")
        case .bigstoneNeutralsValue40:
            return Color(hex: "#888888")
        case .bigstonePrimaryValue40:
            return Color(hex: "#5EAAD2")
        case .bigstoneSecondaryValue40:
            return Color(hex: "#5ACE86")
        case .plumNeutralsValue40:
            return Color(hex: "#888888")
        case .plumPrimaryValue40:
            return Color(hex: "#D29AD8")
        case .plumSecondaryValue40:
            return Color(hex: "#5ACE86")
        case .bigstonePrimaryValue5:
            return Color(hex: "#F3F8FC")
        case .bigstoneSecondaryValue5:
            return Color(hex: "#F1FCF5")
        case .plumPrimaryValue5:
            return Color(hex: "#FBF7FC")
        case .plumSecondaryValue5:
            return Color(hex: "#F1FCF5")
        case .bigstoneNeutralsValue50:
            return Color(hex: "#6D6D6D")
        case .bigstonePrimaryValue50:
            return Color(hex: "#3A8FBD")
        case .bigstoneSecondaryValue50:
            return Color(hex: "#33B465")
        case .plumNeutralsValue50:
            return Color(hex: "#6D6D6D")
        case .plumPrimaryValue50:
            return Color(hex: "#BB71C4")
        case .plumSecondaryValue50:
            return Color(hex: "#33B465")
        case .bigstoneNeutralsValue60:
            return Color(hex: "#5D5D5D")
        case .bigstonePrimaryValue60:
            return Color(hex: "#2973A0")
        case .bigstoneSecondaryValue60:
            return Color(hex: "#25944F")
        case .plumNeutralsValue60:
            return Color(hex: "#5D5D5D")
        case .plumPrimaryValue60:
            return Color(hex: "#A152A7")
        case .plumSecondaryValue60:
            return Color(hex: "#25944F")
        case .bigstoneNeutralsValue70:
            return Color(hex: "#4F4F4F")
        case .bigstonePrimaryValue70:
            return Color(hex: "#235D81")
        case .bigstoneSecondaryValue70:
            return Color(hex: "#207541")
        case .plumNeutralsValue70:
            return Color(hex: "#4F4F4F")
        case .plumPrimaryValue70:
            return Color(hex: "#7E3E82")
        case .plumSecondaryValue70:
            return Color(hex: "#207541")
        case .bigstoneNeutralsValue80:
            return Color(hex: "#454545")
        case .bigstonePrimaryValue80:
            return Color(hex: "#204E6C")
        case .bigstoneSecondaryValue80:
            return Color(hex: "#1E5D37")
        case .plumNeutralsValue80:
            return Color(hex: "#454545")
        case .plumPrimaryValue80:
            return Color(hex: "#6E3771")
        case .plumSecondaryValue80:
            return Color(hex: "#1E5D37")
        case .bigstoneNeutralsValue90:
            return Color(hex: "#3D3D3D")
        case .bigstonePrimaryValue90:
            return Color(hex: "#20435A")
        case .bigstoneSecondaryValue90:
            return Color(hex: "#153C25")
        case .plumNeutralsValue90:
            return Color(hex: "#3D3D3D")
        case .plumPrimaryValue90:
            return Color(hex: "#5C315E")
        case .plumSecondaryValue90:
            return Color(hex: "#153C25")
        case .bigstoneNeutralsValue95:
            return Color(hex: "#181818")
        case .bigstonePrimaryValue95:
            return Color(hex: "#152B3C")
        case .bigstoneSecondaryValue95:
            return Color(hex: "#092A17")
        case .plumNeutralsValue95:
            return Color(hex: "#181818")
        case .plumPrimaryValue95:
            return Color(hex: "#3A173B")
        case .plumSecondaryValue95:
            return Color(hex: "#092A17")
        case .bigstoneRadiusRadiusl:
            return Color(hex: "48.0")
        case .plumRadiusRadiusl:
            return Color(hex: "48.0")
        case .bigstoneRadiusRadiusm:
            return Color(hex: "16.0")
        case .plumRadiusRadiusm:
            return Color(hex: "16.0")
        case .bigstoneRadiusRadiusround:
            return Color(hex: "100.0")
        case .plumRadiusRadiusround:
            return Color(hex: "100.0")
        case .bigstoneRadiusRadiuss:
            return Color(hex: "8.0")
        case .plumRadiusRadiuss:
            return Color(hex: "8.0")
        case .bigstoneRadiusRadiusxl:
            return Color(hex: "64.0")
        case .plumRadiusRadiusxl:
            return Color(hex: "64.0")
        case .bigstoneRadiusRadiusxs:
            return Color(hex: "4.0")
        case .plumRadiusRadiusxs:
            return Color(hex: "4.0")
        case .bigstoneSpacingSpacing01:
            return Color(hex: "4.0")
        case .plumSpacingSpacing01:
            return Color(hex: "4.0")
        case .bigstoneSpacingSpacing02:
            return Color(hex: "8.0")
        case .plumSpacingSpacing02:
            return Color(hex: "8.0")
        case .bigstoneSpacingSpacing03:
            return Color(hex: "16.0")
        case .plumSpacingSpacing03:
            return Color(hex: "16.0")
        case .bigstoneSpacingSpacing04:
            return Color(hex: "24.0")
        case .plumSpacingSpacing04:
            return Color(hex: "24.0")
        case .bigstoneSpacingSpacing05:
            return Color(hex: "32.0")
        case .plumSpacingSpacing05:
            return Color(hex: "32.0")
        case .bigstoneSpacingSpacing06:
            return Color(hex: "40.0")
        case .plumSpacingSpacing06:
            return Color(hex: "40.0")
        case .bigstoneSpacingSpacing07:
            return Color(hex: "48.0")
        case .plumSpacingSpacing07:
            return Color(hex: "48.0")
        case .bigstoneSpacingSpacing08:
            return Color(hex: "56.0")
        case .plumSpacingSpacing08:
            return Color(hex: "56.0")
        case .bigstoneSpacingSpacing09:
            return Color(hex: "64.0")
        case .plumSpacingSpacing09:
            return Color(hex: "64.0")
        case .bigstoneSpacingSpacing10:
            return Color(hex: "72.0")
        case .plumSpacingSpacing10:
            return Color(hex: "72.0")
        }
    }
}

