// Generated by umain-design-tokens-pipeline
// Do not edit this file manually

import SwiftUI
import Foundation
#if canImport(UIKit)
import UIKit
#endif
#if canImport(AppKit)
import AppKit
#endif

// MARK: - SemanticColors

/// Adaptive colors that switch between light and dark values.
/// Usage: SemanticColors.someToken
public enum SemanticColors: String, CaseIterable {
    /// Accent - Light: #FFFFFF, Dark: #262626
    /// Category: bg
    case accent = "accent"
    /// AccentAccessible - Light: #B08000, Dark: #FFAA00
    /// Category: fg
    case accentAccessible = "accentAccessible"
    /// Accent1 - Light: #920847, Dark: #FF7DB8
    /// Category: fg
    case accent1 = "accent1"
    /// Accent2 - Light: #B24C00, Dark: #FFF8F3
    /// Category: fg
    case accent2 = "accent2"
    /// Accent3 - Light: #ED7F42, Dark: #ED7F42
    /// Category: fg
    case accent3 = "accent3"
    /// Active - Light: #262626, Dark: #FFFFFF
    /// Category: stroke
    case active = "active"
    /// BgBrand - Light: #FFAA00, Dark: #FFAA00
    /// Category: bg
    case BgBrand = "BgBrand"
    /// StrokeBrand - Light: #FFAA00, Dark: #FFAA00
    /// Category: stroke
    case StrokeBrand = "StrokeBrand"
    /// ColorOnBrand - Light: #262626, Dark: #262626
    /// Category: fg
    case colorOnBrand = "colorOnBrand"
    /// Divider - Light: #D4D4D4, Dark: #6D6D6D
    /// Category: fg
    case divider = "divider"
    /// BgError - Light: #FEF3F3, Dark: #FC5C624D
    /// Category: bg
    case BgError = "BgError"
    /// FgError - Light: #CC0008, Dark: #FEF3F3
    /// Category: fg
    case FgError = "FgError"
    /// StrokeError - Light: #CC0008, Dark: #FC5C62
    /// Category: stroke
    case StrokeError = "StrokeError"
    /// BgInverted - Light: #262626, Dark: #FFFFFF
    /// Category: bg
    case BgInverted = "BgInverted"
    /// FgInverted - Light: #FFFFFF, Dark: #262626
    /// Category: fg
    case FgInverted = "FgInverted"
    /// Link - Light: #005FA3, Dark: #3DB5FF
    /// Category: fg
    case link = "link"
    /// BgPrimary - Light: #F8F8F8, Dark: #262626
    /// Category: bg
    case BgPrimary = "BgPrimary"
    /// FgPrimary - Light: #262626, Dark: #FFFFFF
    /// Category: fg
    case FgPrimary = "FgPrimary"
    /// StrokePrimary - Light: #26262633, Dark: #FFFFFF33
    /// Category: stroke
    case StrokePrimary = "StrokePrimary"
    /// PrimaryDisabled - Light: #FCE8B0, Dark: #FCE8B0
    /// It is used only in design to visualize element state backgrounds
    /// Category: interactive
    case primaryDisabled = "primaryDisabled"
    /// PrimaryPressed - Light: #B08000, Dark: #B08000
    /// It is used only in design to visualize element state backgrounds
    /// Category: interactive
    case primaryPressed = "primaryPressed"
    /// Quaternary - Light: #D4D4D4, Dark: #6D6D6D
    /// Category: fg
    case quaternary = "quaternary"
    /// BgSecondary - Light: #FFFFFF, Dark: #181818
    /// Category: bg
    case BgSecondary = "BgSecondary"
    /// FgSecondary - Light: #6D6D6D, Dark: #D4D4D4
    /// Category: fg
    case FgSecondary = "FgSecondary"
    /// StrokeSecondary - Light: #6D6D6D, Dark: #F2F2F2
    /// Category: stroke
    case StrokeSecondary = "StrokeSecondary"
    /// SecondaryPressed - Light: #D4D4D4, Dark: #6D6D6D
    /// It is used only in design to visualize element state backgrounds
    /// Category: interactive
    case secondaryPressed = "secondaryPressed"
    /// BgSuccess - Light: #F2F6F3, Dark: #4DAE6E4D
    /// Category: bg
    case BgSuccess = "BgSuccess"
    /// FgSuccess - Light: #224830, Dark: #4DAE6E
    /// Category: fg
    case FgSuccess = "FgSuccess"
    /// StrokeSuccess - Light: #224830, Dark: #4DAE6E
    /// Category: stroke
    case StrokeSuccess = "StrokeSuccess"
    /// BgTertiary - Light: #F2F2F2, Dark: #3A3A3A
    /// Category: bg
    case BgTertiary = "BgTertiary"
    /// FgTertiary - Light: #ABABAB, Dark: #939393
    /// Category: fg
    case FgTertiary = "FgTertiary"
    /// StrokeTertiary - Light: #D4D4D4, Dark: #6D6D6D
    /// Category: stroke
    case StrokeTertiary = "StrokeTertiary"
    /// BgWarning - Light: #FFF8F3, Dark: #ED7F424D
    /// Category: bg
    case BgWarning = "BgWarning"
    /// StrokeWarning - Light: #B24C00, Dark: #ED7F42
    /// Category: stroke
    case StrokeWarning = "StrokeWarning"
}

// MARK: - Semantic Color Category (matches Figma)

/// Semantic color category for grouping in UI.
public enum SemanticColorCategory: String, CaseIterable {
    case bg
    case fg
    case stroke
    case interactive
}

public extension SemanticColors {
    /// Category for showcase grouping (matches Figma).
    var category: SemanticColorCategory {
        switch self {
        case .accent: return .bg
        case .accentAccessible: return .fg
        case .accent1: return .fg
        case .accent2: return .fg
        case .accent3: return .fg
        case .active: return .stroke
        case .BgBrand: return .bg
        case .StrokeBrand: return .stroke
        case .colorOnBrand: return .fg
        case .divider: return .fg
        case .BgError: return .bg
        case .FgError: return .fg
        case .StrokeError: return .stroke
        case .BgInverted: return .bg
        case .FgInverted: return .fg
        case .link: return .fg
        case .BgPrimary: return .bg
        case .FgPrimary: return .fg
        case .StrokePrimary: return .stroke
        case .primaryDisabled: return .interactive
        case .primaryPressed: return .interactive
        case .quaternary: return .fg
        case .BgSecondary: return .bg
        case .FgSecondary: return .fg
        case .StrokeSecondary: return .stroke
        case .secondaryPressed: return .interactive
        case .BgSuccess: return .bg
        case .FgSuccess: return .fg
        case .StrokeSuccess: return .stroke
        case .BgTertiary: return .bg
        case .FgTertiary: return .fg
        case .StrokeTertiary: return .stroke
        case .BgWarning: return .bg
        case .StrokeWarning: return .stroke
        }
    }
}

#if os(iOS)
public extension UIColor {
    static func semantic(_ token: SemanticColors) -> UIColor {
        UIColor { trait in
            let isDark = (trait.userInterfaceStyle == .dark)
            switch token {
            case .accent:
                return isDark ? UIColor(hex: "#262626") : UIColor(hex: "#FFFFFF")
            case .accentAccessible:
                return isDark ? UIColor(hex: "#FFAA00") : UIColor(hex: "#B08000")
            case .accent1:
                return isDark ? UIColor(hex: "#FF7DB8") : UIColor(hex: "#920847")
            case .accent2:
                return isDark ? UIColor(hex: "#FFF8F3") : UIColor(hex: "#B24C00")
            case .accent3:
                return isDark ? UIColor(hex: "#ED7F42") : UIColor(hex: "#ED7F42")
            case .active:
                return isDark ? UIColor(hex: "#FFFFFF") : UIColor(hex: "#262626")
            case .BgBrand:
                return isDark ? UIColor(hex: "#FFAA00") : UIColor(hex: "#FFAA00")
            case .StrokeBrand:
                return isDark ? UIColor(hex: "#FFAA00") : UIColor(hex: "#FFAA00")
            case .colorOnBrand:
                return isDark ? UIColor(hex: "#262626") : UIColor(hex: "#262626")
            case .divider:
                return isDark ? UIColor(hex: "#6D6D6D") : UIColor(hex: "#D4D4D4")
            case .BgError:
                return isDark ? UIColor(hex: "#FC5C624D") : UIColor(hex: "#FEF3F3")
            case .FgError:
                return isDark ? UIColor(hex: "#FEF3F3") : UIColor(hex: "#CC0008")
            case .StrokeError:
                return isDark ? UIColor(hex: "#FC5C62") : UIColor(hex: "#CC0008")
            case .BgInverted:
                return isDark ? UIColor(hex: "#FFFFFF") : UIColor(hex: "#262626")
            case .FgInverted:
                return isDark ? UIColor(hex: "#262626") : UIColor(hex: "#FFFFFF")
            case .link:
                return isDark ? UIColor(hex: "#3DB5FF") : UIColor(hex: "#005FA3")
            case .BgPrimary:
                return isDark ? UIColor(hex: "#262626") : UIColor(hex: "#F8F8F8")
            case .FgPrimary:
                return isDark ? UIColor(hex: "#FFFFFF") : UIColor(hex: "#262626")
            case .StrokePrimary:
                return isDark ? UIColor(hex: "#FFFFFF33") : UIColor(hex: "#26262633")
            case .primaryDisabled:
                return isDark ? UIColor(hex: "#FCE8B0") : UIColor(hex: "#FCE8B0")
            case .primaryPressed:
                return isDark ? UIColor(hex: "#B08000") : UIColor(hex: "#B08000")
            case .quaternary:
                return isDark ? UIColor(hex: "#6D6D6D") : UIColor(hex: "#D4D4D4")
            case .BgSecondary:
                return isDark ? UIColor(hex: "#181818") : UIColor(hex: "#FFFFFF")
            case .FgSecondary:
                return isDark ? UIColor(hex: "#D4D4D4") : UIColor(hex: "#6D6D6D")
            case .StrokeSecondary:
                return isDark ? UIColor(hex: "#F2F2F2") : UIColor(hex: "#6D6D6D")
            case .secondaryPressed:
                return isDark ? UIColor(hex: "#6D6D6D") : UIColor(hex: "#D4D4D4")
            case .BgSuccess:
                return isDark ? UIColor(hex: "#4DAE6E4D") : UIColor(hex: "#F2F6F3")
            case .FgSuccess:
                return isDark ? UIColor(hex: "#4DAE6E") : UIColor(hex: "#224830")
            case .StrokeSuccess:
                return isDark ? UIColor(hex: "#4DAE6E") : UIColor(hex: "#224830")
            case .BgTertiary:
                return isDark ? UIColor(hex: "#3A3A3A") : UIColor(hex: "#F2F2F2")
            case .FgTertiary:
                return isDark ? UIColor(hex: "#939393") : UIColor(hex: "#ABABAB")
            case .StrokeTertiary:
                return isDark ? UIColor(hex: "#6D6D6D") : UIColor(hex: "#D4D4D4")
            case .BgWarning:
                return isDark ? UIColor(hex: "#ED7F424D") : UIColor(hex: "#FFF8F3")
            case .StrokeWarning:
                return isDark ? UIColor(hex: "#ED7F42") : UIColor(hex: "#B24C00")
            }
        }
    }
}
#endif // os(iOS)

#if os(iOS)
@available(iOS 17.0, *)
public extension Color {
    /// Returns a dynamic color that automatically adapts to light/dark mode.
    /// Uses UIColor trait provider under the hood, so it updates instantly when appearance changes.
    /// No need to pass `colorScheme` or use `@Environment` — just call `Color.semantic(.token)`.
    static func semantic(_ token: SemanticColors) -> Color {
        Color(UIColor.semantic(token))
    }
}
#endif // os(iOS)

