// Generated by umain-design-tokens-pipeline
// Do not edit this file manually

import SwiftUI
import Foundation
#if canImport(UIKit)
import UIKit
#endif
#if canImport(AppKit)
import AppKit
#endif

// MARK: - SemanticColors

/// Adaptive colors that switch between light and dark values.
/// Usage: SemanticColors.someToken
public enum SemanticColors: String, CaseIterable {
    /// Accent - Light: #FFFFFF, Dark: #292929
    /// Category: bg
    case accent = "accent"
    /// AccentAccessible - Light: #C08B00, Dark: #FFBC0D
    /// Category: fg
    case accentAccessible = "accentAccessible"
    /// Accent1 - Light: #9A0A4D, Dark: #FF8FC3
    /// Category: fg
    case accent1 = "accent1"
    /// Accent2 - Light: #BE5100, Dark: #FFF9F5
    /// Category: fg
    case accent2 = "accent2"
    /// Accent3 - Light: #EF8849, Dark: #EF8849
    /// Category: fg
    case accent3 = "accent3"
    /// Active - Light: #292929, Dark: #FFFFFF
    /// Category: stroke
    case active = "active"
    /// BgBrand - Light: #FFBC0D, Dark: #FFBC0D
    /// Category: bg
    case BgBrand = "BgBrand"
    /// StrokeBrand - Light: #FFBC0D, Dark: #FFBC0D
    /// Category: stroke
    case StrokeBrand = "StrokeBrand"
    /// ColorOnBrand - Light: #292929, Dark: #292929
    /// Category: fg
    case colorOnBrand = "colorOnBrand"
    /// Divider - Light: #D6D6D6, Dark: #6F6F6F
    /// Category: fg
    case divider = "divider"
    /// BgError - Light: #FDF2F2, Dark: #FD686D4D
    /// Category: bg
    case BgError = "BgError"
    /// FgError - Light: #DB0007, Dark: #FDF2F2
    /// Category: fg
    case FgError = "FgError"
    /// StrokeError - Light: #DB0007, Dark: #FD686D
    /// Category: stroke
    case StrokeError = "StrokeError"
    /// BgInverted - Light: #292929, Dark: #FFFFFF
    /// Category: bg
    case BgInverted = "BgInverted"
    /// FgInverted - Light: #FFFFFF, Dark: #292929
    /// Category: fg
    case FgInverted = "FgInverted"
    /// Link - Light: #006BAE, Dark: #4DBBFF
    /// Category: fg
    case link = "link"
    /// BgPrimary - Light: #F9F9F9, Dark: #292929
    /// Category: bg
    case BgPrimary = "BgPrimary"
    /// FgPrimary - Light: #292929, Dark: #FFFFFF
    /// Category: fg
    case FgPrimary = "FgPrimary"
    /// StrokePrimary - Light: #29292933, Dark: #FFFFFF33
    /// Category: stroke
    case StrokePrimary = "StrokePrimary"
    /// PrimaryDisabled - Light: #FBE4A7, Dark: #FBE4A7
    /// It is used only in design to visualize element state backgrounds
    /// Category: interactive
    case primaryDisabled = "primaryDisabled"
    /// PrimaryPressed - Light: #C08B00, Dark: #C08B00
    /// It is used only in design to visualize element state backgrounds
    /// Category: interactive
    case primaryPressed = "primaryPressed"
    /// Quaternary - Light: #D6D6D6, Dark: #6F6F6F
    /// Category: fg
    case quaternary = "quaternary"
    /// BgSecondary - Light: #FFFFFF, Dark: #1B1B1B
    /// Category: bg
    case BgSecondary = "BgSecondary"
    /// FgSecondary - Light: #6F6F6F, Dark: #D6D6D6
    /// Category: fg
    case FgSecondary = "FgSecondary"
    /// StrokeSecondary - Light: #6F6F6F, Dark: #F3F3F3
    /// Category: stroke
    case StrokeSecondary = "StrokeSecondary"
    /// SecondaryPressed - Light: #D6D6D6, Dark: #6F6F6F
    /// It is used only in design to visualize element state backgrounds
    /// Category: interactive
    case secondaryPressed = "secondaryPressed"
    /// BgSuccess - Light: #F4F7F5, Dark: #54B0774D
    /// Category: bg
    case BgSuccess = "BgSuccess"
    /// FgSuccess - Light: #264F36, Dark: #54B077
    /// Category: fg
    case FgSuccess = "FgSuccess"
    /// StrokeSuccess - Light: #264F36, Dark: #54B077
    /// Category: stroke
    case StrokeSuccess = "StrokeSuccess"
    /// BgTertiary - Light: #F3F3F3, Dark: #3D3D3D
    /// Category: bg
    case BgTertiary = "BgTertiary"
    /// FgTertiary - Light: #ADADAD, Dark: #959595
    /// Category: fg
    case FgTertiary = "FgTertiary"
    /// StrokeTertiary - Light: #D6D6D6, Dark: #6F6F6F
    /// Category: stroke
    case StrokeTertiary = "StrokeTertiary"
    /// BgWarning - Light: #FFF9F5, Dark: #EF88494D
    /// Category: bg
    case BgWarning = "BgWarning"
    /// StrokeWarning - Light: #BE5100, Dark: #EF8849
    /// Category: stroke
    case StrokeWarning = "StrokeWarning"
}

// MARK: - Semantic Color Category (matches Figma)

/// Semantic color category for grouping in UI.
public enum SemanticColorCategory: String, CaseIterable {
    case bg
    case fg
    case stroke
    case interactive
}

public extension SemanticColors {
    /// Category for showcase grouping (matches Figma).
    var category: SemanticColorCategory {
        switch self {
        case .accent: return .bg
        case .accentAccessible: return .fg
        case .accent1: return .fg
        case .accent2: return .fg
        case .accent3: return .fg
        case .active: return .stroke
        case .BgBrand: return .bg
        case .StrokeBrand: return .stroke
        case .colorOnBrand: return .fg
        case .divider: return .fg
        case .BgError: return .bg
        case .FgError: return .fg
        case .StrokeError: return .stroke
        case .BgInverted: return .bg
        case .FgInverted: return .fg
        case .link: return .fg
        case .BgPrimary: return .bg
        case .FgPrimary: return .fg
        case .StrokePrimary: return .stroke
        case .primaryDisabled: return .interactive
        case .primaryPressed: return .interactive
        case .quaternary: return .fg
        case .BgSecondary: return .bg
        case .FgSecondary: return .fg
        case .StrokeSecondary: return .stroke
        case .secondaryPressed: return .interactive
        case .BgSuccess: return .bg
        case .FgSuccess: return .fg
        case .StrokeSuccess: return .stroke
        case .BgTertiary: return .bg
        case .FgTertiary: return .fg
        case .StrokeTertiary: return .stroke
        case .BgWarning: return .bg
        case .StrokeWarning: return .stroke
        }
    }
}

#if os(iOS)
public extension UIColor {
    static func semantic(_ token: SemanticColors) -> UIColor {
        UIColor { trait in
            let isDark = (trait.userInterfaceStyle == .dark)
            switch token {
            case .accent:
                return isDark ? UIColor(hex: "#292929") : UIColor(hex: "#FFFFFF")
            case .accentAccessible:
                return isDark ? UIColor(hex: "#FFBC0D") : UIColor(hex: "#C08B00")
            case .accent1:
                return isDark ? UIColor(hex: "#FF8FC3") : UIColor(hex: "#9A0A4D")
            case .accent2:
                return isDark ? UIColor(hex: "#FFF9F5") : UIColor(hex: "#BE5100")
            case .accent3:
                return isDark ? UIColor(hex: "#EF8849") : UIColor(hex: "#EF8849")
            case .active:
                return isDark ? UIColor(hex: "#FFFFFF") : UIColor(hex: "#292929")
            case .BgBrand:
                return isDark ? UIColor(hex: "#FFBC0D") : UIColor(hex: "#FFBC0D")
            case .StrokeBrand:
                return isDark ? UIColor(hex: "#FFBC0D") : UIColor(hex: "#FFBC0D")
            case .colorOnBrand:
                return isDark ? UIColor(hex: "#292929") : UIColor(hex: "#292929")
            case .divider:
                return isDark ? UIColor(hex: "#6F6F6F") : UIColor(hex: "#D6D6D6")
            case .BgError:
                return isDark ? UIColor(hex: "#FD686D4D") : UIColor(hex: "#FDF2F2")
            case .FgError:
                return isDark ? UIColor(hex: "#FDF2F2") : UIColor(hex: "#DB0007")
            case .StrokeError:
                return isDark ? UIColor(hex: "#FD686D") : UIColor(hex: "#DB0007")
            case .BgInverted:
                return isDark ? UIColor(hex: "#FFFFFF") : UIColor(hex: "#292929")
            case .FgInverted:
                return isDark ? UIColor(hex: "#292929") : UIColor(hex: "#FFFFFF")
            case .link:
                return isDark ? UIColor(hex: "#4DBBFF") : UIColor(hex: "#006BAE")
            case .BgPrimary:
                return isDark ? UIColor(hex: "#292929") : UIColor(hex: "#F9F9F9")
            case .FgPrimary:
                return isDark ? UIColor(hex: "#FFFFFF") : UIColor(hex: "#292929")
            case .StrokePrimary:
                return isDark ? UIColor(hex: "#FFFFFF33") : UIColor(hex: "#29292933")
            case .primaryDisabled:
                return isDark ? UIColor(hex: "#FBE4A7") : UIColor(hex: "#FBE4A7")
            case .primaryPressed:
                return isDark ? UIColor(hex: "#C08B00") : UIColor(hex: "#C08B00")
            case .quaternary:
                return isDark ? UIColor(hex: "#6F6F6F") : UIColor(hex: "#D6D6D6")
            case .BgSecondary:
                return isDark ? UIColor(hex: "#1B1B1B") : UIColor(hex: "#FFFFFF")
            case .FgSecondary:
                return isDark ? UIColor(hex: "#D6D6D6") : UIColor(hex: "#6F6F6F")
            case .StrokeSecondary:
                return isDark ? UIColor(hex: "#F3F3F3") : UIColor(hex: "#6F6F6F")
            case .secondaryPressed:
                return isDark ? UIColor(hex: "#6F6F6F") : UIColor(hex: "#D6D6D6")
            case .BgSuccess:
                return isDark ? UIColor(hex: "#54B0774D") : UIColor(hex: "#F4F7F5")
            case .FgSuccess:
                return isDark ? UIColor(hex: "#54B077") : UIColor(hex: "#264F36")
            case .StrokeSuccess:
                return isDark ? UIColor(hex: "#54B077") : UIColor(hex: "#264F36")
            case .BgTertiary:
                return isDark ? UIColor(hex: "#3D3D3D") : UIColor(hex: "#F3F3F3")
            case .FgTertiary:
                return isDark ? UIColor(hex: "#959595") : UIColor(hex: "#ADADAD")
            case .StrokeTertiary:
                return isDark ? UIColor(hex: "#6F6F6F") : UIColor(hex: "#D6D6D6")
            case .BgWarning:
                return isDark ? UIColor(hex: "#EF88494D") : UIColor(hex: "#FFF9F5")
            case .StrokeWarning:
                return isDark ? UIColor(hex: "#EF8849") : UIColor(hex: "#BE5100")
            }
        }
    }
}
#endif // os(iOS)

#if os(iOS)
@available(iOS 17.0, *)
public extension Color {
    /// Returns a dynamic color that automatically adapts to light/dark mode.
    /// Uses UIColor trait provider under the hood, so it updates instantly when appearance changes.
    /// No need to pass `colorScheme` or use `@Environment` — just call `Color.semantic(.token)`.
    static func semantic(_ token: SemanticColors) -> Color {
        Color(UIColor.semantic(token))
    }
}
#endif // os(iOS)

