// Generated by UmainDesignToken
// Do not edit this file manually

import SwiftUI
#if canImport(UIKit)
import UIKit
#endif

// MARK: - Spacing

/// Spacing tokens.
/// Usage: Spacing.someToken.value
public enum Spacing: CaseIterable {
    case horizontalSafeAreaInset(CGFloat), large(CGFloat), medium(CGFloat), scrollViewBottomPadding(CGFloat), small(CGFloat), touchAreaMinimum(CGFloat), xlarge(CGFloat), xsmall(CGFloat), xxlarge(CGFloat), xxsmall(CGFloat), xxxlarge(CGFloat), xxxxlarge(CGFloat)

    public var value: CGFloat {
        switch self {
        case .horizontalSafeAreaInset(let value):
            return value
        case .large(let value):
            return value
        case .medium(let value):
            return value
        case .scrollViewBottomPadding(let value):
            return value
        case .small(let value):
            return value
        case .touchAreaMinimum(let value):
            return value
        case .xlarge(let value):
            return value
        case .xsmall(let value):
            return value
        case .xxlarge(let value):
            return value
        case .xxsmall(let value):
            return value
        case .xxxlarge(let value):
            return value
        case .xxxxlarge(let value):
            return value
        }
    }

    // MARK: - Static Convenience Properties

    /// Horizontalsafeareainset
    /// Category: 
    public static let horizontalSafeAreaInset: Spacing = .horizontalSafeAreaInset(56.0)

    /// Large
    /// Category: 
    public static let large: Spacing = .large(16.0)

    /// Medium
    /// Category: 
    public static let medium: Spacing = .medium(12.0)

    /// Scrollviewbottompadding
    /// Extra padding at the bottom of scrollview to ensure content never gets hidden behind a floating bar or toast.
    /// Category: 
    public static let scrollViewBottomPadding: Spacing = .scrollViewBottomPadding(80.0)

    /// Small
    /// Category: 
    public static let small: Spacing = .small(8.0)

    /// Touchareaminimum
    /// Category: 
    public static let touchAreaMinimum: Spacing = .touchAreaMinimum(44.0)

    /// Xlarge
    /// Category: 
    public static let xlarge: Spacing = .xlarge(20.0)

    /// Xsmall
    /// Category: 
    public static let xsmall: Spacing = .xsmall(4.0)

    /// Xxlarge
    /// Category: 
    public static let xxlarge: Spacing = .xxlarge(24.0)

    /// Xxsmall
    /// Category: 
    public static let xxsmall: Spacing = .xxsmall(2.0)

    /// Xxxlarge
    /// Category: 
    public static let xxxlarge: Spacing = .xxxlarge(32.0)

    /// Xxxxlarge
    /// Category: 
    public static let xxxxlarge: Spacing = .xxxxlarge(40.0)

    public static var allCases: [Spacing] {
        [
            .horizontalSafeAreaInset,
            .large,
            .medium,
            .scrollViewBottomPadding,
            .small,
            .touchAreaMinimum,
            .xlarge,
            .xsmall,
            .xxlarge,
            .xxsmall,
            .xxxlarge,
            .xxxxlarge,
        ]
    }
}

