// Generated by umain-design-tokens-pipeline
// Do not edit this file manually

import SwiftUI
import Foundation
#if canImport(UIKit)
import UIKit
#endif
#if canImport(AppKit)
import AppKit
#endif

// MARK: - SpatialSystem

/// SpatialSystem tokens.
/// Usage: `SpatialSystem.l.value`
public enum SpatialSystem: CGFloat, CaseIterable {
    /// HorizontalSafeAreaInset - 56.0
    case horizontalSafeAreaInset = 56.0
    /// Large - 16.0
    case large = 16.0
    /// Medium - 12.0
    case medium = 12.0
    /// ScrollViewBottomPadding - 80.0
    /// Extra padding at the bottom of scrollview to ensure content never gets hidden behind a floating bar or toast.
    case scrollViewBottomPadding = 80.0
    /// Small - 8.0
    case small = 8.0
    /// TouchAreaMinimum - 44.0
    case touchAreaMinimum = 44.0
    /// Xlarge - 20.0
    case xlarge = 20.0
    /// Xsmall - 4.0
    case xsmall = 4.0
    /// Xxlarge - 24.0
    case xxlarge = 24.0
    /// Xxsmall - 2.0
    case xxsmall = 2.0
    /// Xxxlarge - 32.0
    case xxxlarge = 32.0
    /// Xxxxlarge - 40.0
    case xxxxlarge = 40.0

    /// Returns the numeric value of the token.
    public var value: CGFloat { rawValue }
}

// MARK: - SwiftUI Convenience Extensions

extension View {
    /// Apply padding using a SpatialSystem token value.
    /// - Parameter size: The spatial system token to use for padding
    /// - Returns: A view with the specified padding applied to all edges
    public func padding(_ size: SpatialSystem) -> some View {
        padding(size.value)
    }
    
    /// Apply padding to specific edges using a SpatialSystem token value.
    /// - Parameters:
    ///   - edges: The edges to apply padding to
    ///   - size: The spatial system token to use for padding
    /// - Returns: A view with the specified padding applied to the given edges
    /// Note: For negative values or custom calculations, extract the value first:
    ///   `.padding(.horizontal, -SpatialSystem.xxlarge.value)`
    public func padding(_ edges: Edge.Set, _ size: SpatialSystem) -> some View {
        self.padding(edges, size.value)
    }
}
