// Generated by UmainDesignToken
// Do not edit this file manually

import SwiftUI
#if canImport(UIKit)
import UIKit
#endif

// MARK: - Tokens

/// Tokens tokens.
/// Usage: Tokens.someToken.value
public enum Tokens: CaseIterable {
    /// DarkBorderBorderbrandconstrast - #96C7E3
    /// Category: Dark/colors/border
    case darkBorderBorderbrandconstrast
    /// LightBorderBorderbrandconstrast - #3A8FBD
    /// Category: Light/colors/border
    case lightBorderBorderbrandconstrast
    /// DarkBorderBorderprimary - #E6F0F8
    /// Category: Dark/colors/border
    case darkBorderBorderprimary
    /// LightBorderBorderprimary - #D1D1D1
    /// Category: Light/colors/border
    case lightBorderBorderprimary
    /// DarkSurfaceSurfacebrand - #152B3C
    /// Category: Dark/colors/surface
    case darkSurfaceSurfacebrand
    /// LightSurfaceSurfacebrand - #F3F8FC
    /// Category: Light/colors/surface
    case lightSurfaceSurfacebrand
    /// DarkSurfaceSurfacebrandcontrast - #96C7E3
    /// Category: Dark/colors/surface
    case darkSurfaceSurfacebrandcontrast
    /// LightSurfaceSurfacebrandcontrast - #2973A0
    /// Category: Light/colors/surface
    case lightSurfaceSurfacebrandcontrast
    /// DarkSurfaceSurfacebrandcontrastdisabled - #204E6C
    /// Category: Dark/colors/surface
    case darkSurfaceSurfacebrandcontrastdisabled
    /// LightSurfaceSurfacebrandcontrastdisabled - #C7E1F0
    /// Category: Light/colors/surface
    case lightSurfaceSurfacebrandcontrastdisabled
    /// DarkSurfaceSurfacebrandcontrasthover - #5EAAD2
    /// Category: Dark/colors/surface
    case darkSurfaceSurfacebrandcontrasthover
    /// LightSurfaceSurfacebrandcontrasthover - #235D81
    /// Category: Light/colors/surface
    case lightSurfaceSurfacebrandcontrasthover
    /// DarkSurfaceSurfacebrandcontrastpressed - #3A8FBD
    /// Category: Dark/colors/surface
    case darkSurfaceSurfacebrandcontrastpressed
    /// LightSurfaceSurfacebrandcontrastpressed - #204E6C
    /// Category: Light/colors/surface
    case lightSurfaceSurfacebrandcontrastpressed
    /// DarkSurfaceSurfaceprimary - #181818
    /// Category: Dark/colors/surface
    case darkSurfaceSurfaceprimary
    /// LightSurfaceSurfaceprimary - #FFFFFF
    /// Category: Light/colors/surface
    case lightSurfaceSurfaceprimary
    /// DarkSurfaceSurfaceprimaryhover - #20435A
    /// Category: Dark/colors/surface
    case darkSurfaceSurfaceprimaryhover
    /// LightSurfaceSurfaceprimaryhover - #F3F8FC
    /// Category: Light/colors/surface
    case lightSurfaceSurfaceprimaryhover
    /// DarkSurfaceSurfaceprimarypressed - #152B3C
    /// Category: Dark/colors/surface
    case darkSurfaceSurfaceprimarypressed
    /// LightSurfaceSurfaceprimarypressed - #E6F0F8
    /// Category: Light/colors/surface
    case lightSurfaceSurfaceprimarypressed
    /// DarkTextTextbrand - #20435A
    /// Category: Dark/colors/text
    case darkTextTextbrand
    /// LightTextTextbrand - #20435A
    /// Category: Light/colors/text
    case lightTextTextbrand
    /// DarkTextTextbrandcontrast - #96C7E3
    /// Category: Dark/colors/text
    case darkTextTextbrandcontrast
    /// LightTextTextbrandcontrast - #235D81
    /// Category: Light/colors/text
    case lightTextTextbrandcontrast
    /// DarkTextTextdisabled - #3A8FBD
    /// Category: Dark/colors/text
    case darkTextTextdisabled
    /// LightTextTextdisabled - #3A8FBD
    /// Category: Light/colors/text
    case lightTextTextdisabled
    /// DarkTextTextonbrand - #152B3C
    /// Category: Dark/colors/text
    case darkTextTextonbrand
    /// LightTextTextonbrand - #FFFFFF
    /// Category: Light/colors/text
    case lightTextTextonbrand
    /// DarkTextTextondark - #FFFFFF
    /// Category: Dark/colors/text
    case darkTextTextondark
    /// LightTextTextondark - #FFFFFF
    /// Category: Light/colors/text
    case lightTextTextondark
    /// DarkTextTextprimary - #FFFFFF
    /// Category: Dark/colors/text
    case darkTextTextprimary
    /// LightTextTextprimary - #000000
    /// Category: Light/colors/text
    case lightTextTextprimary

    public var value: Color {
        switch self {
        case .darkBorderBorderbrandconstrast:
            return Color(hex: "#96C7E3")
        case .lightBorderBorderbrandconstrast:
            return Color(hex: "#3A8FBD")
        case .darkBorderBorderprimary:
            return Color(hex: "#E6F0F8")
        case .lightBorderBorderprimary:
            return Color(hex: "#D1D1D1")
        case .darkSurfaceSurfacebrand:
            return Color(hex: "#152B3C")
        case .lightSurfaceSurfacebrand:
            return Color(hex: "#F3F8FC")
        case .darkSurfaceSurfacebrandcontrast:
            return Color(hex: "#96C7E3")
        case .lightSurfaceSurfacebrandcontrast:
            return Color(hex: "#2973A0")
        case .darkSurfaceSurfacebrandcontrastdisabled:
            return Color(hex: "#204E6C")
        case .lightSurfaceSurfacebrandcontrastdisabled:
            return Color(hex: "#C7E1F0")
        case .darkSurfaceSurfacebrandcontrasthover:
            return Color(hex: "#5EAAD2")
        case .lightSurfaceSurfacebrandcontrasthover:
            return Color(hex: "#235D81")
        case .darkSurfaceSurfacebrandcontrastpressed:
            return Color(hex: "#3A8FBD")
        case .lightSurfaceSurfacebrandcontrastpressed:
            return Color(hex: "#204E6C")
        case .darkSurfaceSurfaceprimary:
            return Color(hex: "#181818")
        case .lightSurfaceSurfaceprimary:
            return Color(hex: "#FFFFFF")
        case .darkSurfaceSurfaceprimaryhover:
            return Color(hex: "#20435A")
        case .lightSurfaceSurfaceprimaryhover:
            return Color(hex: "#F3F8FC")
        case .darkSurfaceSurfaceprimarypressed:
            return Color(hex: "#152B3C")
        case .lightSurfaceSurfaceprimarypressed:
            return Color(hex: "#E6F0F8")
        case .darkTextTextbrand:
            return Color(hex: "#20435A")
        case .lightTextTextbrand:
            return Color(hex: "#20435A")
        case .darkTextTextbrandcontrast:
            return Color(hex: "#96C7E3")
        case .lightTextTextbrandcontrast:
            return Color(hex: "#235D81")
        case .darkTextTextdisabled:
            return Color(hex: "#3A8FBD")
        case .lightTextTextdisabled:
            return Color(hex: "#3A8FBD")
        case .darkTextTextonbrand:
            return Color(hex: "#152B3C")
        case .lightTextTextonbrand:
            return Color(hex: "#FFFFFF")
        case .darkTextTextondark:
            return Color(hex: "#FFFFFF")
        case .lightTextTextondark:
            return Color(hex: "#FFFFFF")
        case .darkTextTextprimary:
            return Color(hex: "#FFFFFF")
        case .lightTextTextprimary:
            return Color(hex: "#000000")
        }
    }
}

