// Generated by umain-design-tokens-pipeline
// Do not edit this file manually

import SwiftUI
import Foundation
#if canImport(UIKit)
import UIKit
#endif

#if os(iOS)

/// A compact showcase view that displays all design tokens.
/// Perfect for SwiftUI Previews and design system documentation.
@available(iOS 17.0, *)
public struct TokenShowcaseView: View {
    public init() {}
    
    public var body: some View {
        NavigationView {
            List {
                Section {
                    VStack(alignment: .leading, spacing: 8) {
                        Text("Design Token Showcase")
                            .font(.headline)
                        Text("Auto-generated · Manifest-driven")
                            .font(.caption)
                            .foregroundColor(.secondary)
                    }
                    .padding(.vertical, 8)
                }
                
                Section(header: Text("Typography System").font(.headline)) {
                    NavigationLink(destination: TypographyShowcaseView()) {
                        Text("Typography Styles")
                    }
                }
                
                Section(header: Text("Corner Radius").font(.headline)) {
                    NavigationLink(destination: CornerRadiusShowcase()) {
                        Text("Corner Radius")
                    }
                }
                
                Section(header: Text("Device & Orientation").font(.headline)) {
                    NavigationLink(destination: DeviceAndOrientationShowcase()) {
                        Text("Device & Orientation")
                    }
                }
                
                Section(header: Text("EffectsElevation").font(.headline)) {
                    NavigationLink(destination: EffectsElevationShowcase()) {
                        Text("EffectsElevation")
                    }
                }
                
                Section(header: Text("Gradient Stops").font(.headline)) {
                    NavigationLink(destination: GradientStopsShowcase()) {
                        Text("Gradient Stops")
                    }
                }
                
                Section(header: Text("Icon Size").font(.headline)) {
                    NavigationLink(destination: IconSizeShowcase()) {
                        Text("Icon Size")
                    }
                }
                
                Section(header: Text("Image Size").font(.headline)) {
                    NavigationLink(destination: ImageSizeShowcase()) {
                        Text("Image Size")
                    }
                }
                
                Section(header: Text("Palette").font(.headline)) {
                    NavigationLink(destination: PaletteShowcase()) {
                        Text("Palette")
                    }
                }
                
                Section(header: Text("Semantic Colors").font(.headline)) {
                    NavigationLink(destination: SemanticColorsShowcase()) {
                        Text("Semantic Colors")
                    }
                }
                
                Section(header: Text("Spacing").font(.headline)) {
                    NavigationLink(destination: SpacingShowcase()) {
                        Text("Spacing")
                    }
                }
            }
            .navigationTitle("Design Tokens")
        }
    }
}

// MARK: - UIKit Helpers

// MARK: - Typography Showcase

@available(iOS 17.0, *)
struct TypographyShowcaseView: View {
    var body: some View {
        List {
            Section {
                VStack(alignment: .leading, spacing: 12) {
                    Text("Typography System")
                        .font(.title2)
                        .fontWeight(.bold)
                    Text("All typography styles with unified properties")
                        .font(.caption)
                        .foregroundColor(.secondary)
                }
            }
            
            Section(header: Text("Live Examples")) {
                Text("Heading H0").typography(.h0)
                Text("Heading H1").typography(.h1)
                Text("Paragraph Medium").typography(.paragraphMediumRegular)
                Text("Button Text").typography(.button)
            }
            
            Section(header: Text("Usage")) {
                VStack(alignment: .leading, spacing: 8) {
                    Text(".typography(.h0)")
                        .font(.system(.caption, design: .monospaced))
                        .padding(8)
                        .background(Color.purple.opacity(0.1))
                        .cornerRadius(4)
                    
                    Text(".typography(.paragraphMediumRegular)")
                        .font(.system(.caption, design: .monospaced))
                        .padding(8)
                        .background(Color.purple.opacity(0.1))
                        .cornerRadius(4)
                }
            }
            
            Section(header: Text("All Typography Styles")) {
                ForEach(Array(Typography.allCases), id: \.self) { typography in
                    TypographyStyleRow(typography: typography)
                }
            }
        }
        .navigationTitle("Typography")
        .toolbar {
            Text("\(Typography.allCases.count)")
                .font(.system(.body, design: .monospaced))
                .foregroundColor(.secondary)
        }
    }
}

@available(iOS 17.0, *)
struct TypographyStyleRow: View {
    let typography: Typography
    
    var body: some View {
        VStack(alignment: .leading, spacing: 8) {
            Text("The quick brown fox jumps over the lazy dog")
                .typography(typography)
            
            HStack(spacing: 12) {
                VStack(alignment: .leading, spacing: 2) {
                    Text("Font").font(.caption2).foregroundColor(.secondary)
                    Text(typography.style.fontName).font(.system(.caption2, design: .monospaced))
                }
                VStack(alignment: .leading, spacing: 2) {
                    Text("Size").font(.caption2).foregroundColor(.secondary)
                    Text("\(Int(typography.style.size))pt").font(.system(.caption2, design: .monospaced))
                }
                VStack(alignment: .leading, spacing: 2) {
                    Text("Line Height").font(.caption2).foregroundColor(.secondary)
                    Text("\(Int(typography.style.lineHeight))pt").font(.system(.caption2, design: .monospaced))
                }
                VStack(alignment: .leading, spacing: 2) {
                    Text("Letter Spacing").font(.caption2).foregroundColor(.secondary)
                    Text("\(Int(typography.style.letterSpacingPercent))%").font(.system(.caption2, design: .monospaced))
                }
                VStack(alignment: .leading, spacing: 2) {
                    Text("Dynamic Type").font(.caption2).foregroundColor(.secondary)
                    Text("." + String(describing: typography.relative)).font(.system(.caption2, design: .monospaced))
                }
            }
            .padding(8)
            .background(Color.secondary.opacity(0.05))
            .cornerRadius(6)
            
            HStack {
                Text(String(describing: typography))
                    .font(.system(.caption, design: .monospaced))
                    .foregroundColor(.secondary)
                Spacer()
            }
        }
    }
}

// MARK: - Type-Specific Token Showcases

/// Visual showcase for Corner Radius tokens
@available(iOS 17.0, *)
struct CornerRadiusShowcase: View {
    var body: some View {
        List {
            Section(header: Text("Corner Radius Tokens")) {
                Text("Visual examples of all corner radius values")
                    .font(.caption)
                    .foregroundColor(.secondary)
            }
            
            Section {
                ForEach(Array(CornerRadius.allCases), id: \.self) { radius in
                    CornerRadiusRow(radius: radius)
                }
            }
        }
        .navigationTitle("Corner Radius")
        .toolbar {
            Text("\(CornerRadius.allCases.count)")
                .font(.system(.body, design: .monospaced))
                .foregroundColor(.secondary)
        }
    }
}

@available(iOS 17.0, *)
private struct CornerRadiusRow: View {
    let radius: CornerRadius
    
    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            HStack {
                Text(String(describing: radius).uppercased())
                    .font(.headline)
                Spacer()
                Text("\(Int(radius.value))pt")
                    .font(.system(.body, design: .monospaced))
                    .foregroundColor(.secondary)
            }
            
            RoundedRectangle(cornerRadius: radius.value)
                .fill(Color.blue.opacity(0.2))
                .stroke(Color.blue, lineWidth: 2)
                .frame(height: 80)
        }
        .padding(.vertical, 8)
    }
}

/// Visual showcase for Spacing tokens
@available(iOS 17.0, *)
struct SpacingShowcase: View {
    var body: some View {
        List {
            Section(header: Text("Spacing System")) {
                Text("Spacing between UI elements")
                    .font(.caption)
                    .foregroundColor(.secondary)
            }
            
            Section {
                ForEach(Array(SpatialSystem.allCases), id: \.self) { spacing in
                    VStack(alignment: .leading, spacing: 12) {
                        HStack {
                            Text(String(describing: spacing).uppercased())
                                .font(.headline)
                            Spacer()
                            Text("\(Int(spacing.value))pt")
                                .font(.system(.body, design: .monospaced))
                                .foregroundColor(.secondary)
                        }
                        
                        // Elegant visualization: Two cards with spacing between
                        HStack(spacing: spacing.value) {
                            RoundedRectangle(cornerRadius: 8)
                                .fill(
                                    LinearGradient(
                                        colors: [Color.purple.opacity(0.8), Color.purple.opacity(0.6)],
                                        startPoint: .topLeading,
                                        endPoint: .bottomTrailing
                                    )
                                )
                                .frame(width: 60, height: 50)
                                .shadow(color: Color.black.opacity(0.1), radius: 3, x: 0, y: 2)
                            
                            // Visual spacing indicator
                            ZStack {
                                Rectangle()
                                    .fill(Color.purple.opacity(0.15))
                                    .frame(width: spacing.value, height: 2)
                                
                                VStack(spacing: 2) {
                                    Circle()
                                        .fill(Color.purple.opacity(0.4))
                                        .frame(width: 4, height: 4)
                                    Circle()
                                        .fill(Color.purple.opacity(0.4))
                                        .frame(width: 4, height: 4)
                                    Circle()
                                        .fill(Color.purple.opacity(0.4))
                                        .frame(width: 4, height: 4)
                                }
                            }
                            
                            RoundedRectangle(cornerRadius: 8)
                                .fill(
                                    LinearGradient(
                                        colors: [Color.purple.opacity(0.6), Color.purple.opacity(0.4)],
                                        startPoint: .topLeading,
                                        endPoint: .bottomTrailing
                                    )
                                )
                                .frame(width: 60, height: 50)
                                .shadow(color: Color.black.opacity(0.1), radius: 3, x: 0, y: 2)
                        }
                        .frame(maxWidth: .infinity, alignment: .leading)
                        .padding(.vertical, 4)
                    }
                    .padding(.vertical, 8)
                }
            }
        }
        .navigationTitle("Spacing")
        .toolbar {
            Text("\(SpatialSystem.allCases.count)")
                .font(.system(.body, design: .monospaced))
                .foregroundColor(.secondary)
        }
    }
}

/// Visual showcase for Icon Size tokens
@available(iOS 17.0, *)
struct IconSizeShowcase: View {
    var body: some View {
        List {
            Section(header: Text("Icon Size Tokens")) {
                Text("Visual representation of icon sizes")
                    .font(.caption)
                    .foregroundColor(.secondary)
            }
            
            Section {
                ForEach(Array(IconSize.allCases), id: \.self) { size in
                    IconSizeRow(size: size)
                }
            }
        }
        .navigationTitle("Icon Size")
        .toolbar {
            Text("\(IconSize.allCases.count)")
                .font(.system(.body, design: .monospaced))
                .foregroundColor(.secondary)
        }
    }
}

@available(iOS 17.0, *)
private struct IconSizeRow: View {
    let size: IconSize
    
    var body: some View {
        HStack(spacing: 16) {
            Circle()
                .fill(Color.orange.opacity(0.2))
                .stroke(Color.orange, lineWidth: 2)
                .frame(width: size.value, height: size.value)
            
            VStack(alignment: .leading, spacing: 4) {
                Text(String(describing: size).uppercased())
                    .font(.headline)
                Text("\(Int(size.value)) × \(Int(size.value))pt")
                    .font(.system(.caption, design: .monospaced))
                    .foregroundColor(.secondary)
            }
            
            Spacer()
        }
        .padding(.vertical, 8)
    }
}

/// Visual showcase for Image Size tokens
@available(iOS 17.0, *)
struct ImageSizeShowcase: View {
    var body: some View {
        List {
            Section(header: Text("Image Size Tokens")) {
                Text("Visual representation of image sizes")
                    .font(.caption)
                    .foregroundColor(.secondary)
            }
            
            Section {
                ForEach(Array(ImageSize.allCases), id: \.self) { size in
                    ImageSizeRow(size: size)
                }
            }
        }
        .navigationTitle("Image Size")
        .toolbar {
            Text("\(ImageSize.allCases.count)")
                .font(.system(.body, design: .monospaced))
                .foregroundColor(.secondary)
        }
    }
}

@available(iOS 17.0, *)
private struct ImageSizeRow: View {
    let size: ImageSize
    
    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            HStack {
                Text(String(describing: size).uppercased())
                    .font(.headline)
                Spacer()
                Text("\(Int(size.value)) × \(Int(size.value))pt")
                    .font(.system(.caption, design: .monospaced))
                    .foregroundColor(.secondary)
            }
            
            RoundedRectangle(cornerRadius: 8)
                .fill(Color.green.opacity(0.2))
                .stroke(Color.green, lineWidth: 2)
                .frame(width: size.value, height: size.value)
        }
        .padding(.vertical, 8)
    }
}

/// Visual showcase for Palette colors (grouped by category like Figma: Greyscale, Gold, Red, etc.)
@available(iOS 17.0, *)
struct PaletteShowcase: View {
    private static let categoryOrder: [PaletteColorCategory] = [.greyscale, .gold, .red, .green, .orange, .blue, .fuchsia, .other]
    
    var body: some View {
        List {
            Section(header: Text("UI Palette")) {
                Text("Palette colors grouped by category (matches Figma)")
                    .font(.caption)
                    .foregroundColor(.secondary)
            }
            
            ForEach(Self.categoryOrder, id: \.self) { category in
                let colorsInCategory = Palette.allCases.filter { $0.category == category }
                if !colorsInCategory.isEmpty {
                    Section(header: HStack {
                        Text(categoryDisplayName(category))
                            .font(.subheadline)
                            .fontWeight(.semibold)
                        Spacer()
                        Text("\(colorsInCategory.count)")
                            .font(.system(.caption, design: .monospaced))
                            .foregroundColor(.secondary)
                    }) {
                        ForEach(Array(colorsInCategory), id: \.self) { color in
                            PaletteColorRow(color: color)
                        }
                    }
                }
            }
        }
        .navigationTitle("Palette")
        .toolbar {
            Text("\(Palette.allCases.count)")
                .font(.system(.body, design: .monospaced))
                .foregroundColor(.secondary)
        }
    }
    
    private func categoryDisplayName(_ category: PaletteColorCategory) -> String {
        switch category {
        case .greyscale: return "Greyscale"
        case .gold: return "Gold"
        case .red: return "Red"
        case .green: return "Green"
        case .orange: return "Orange"
        case .blue: return "Blue"
        case .fuchsia: return "Fuchsia"
        case .other: return "Other"
        }
    }
}

@available(iOS 17.0, *)
struct PaletteColorRow: View {
    let color: Palette
    
    var body: some View {
        HStack(spacing: 16) {
            RoundedRectangle(cornerRadius: 8)
                .fill(color.value)
                .frame(width: 60, height: 60)
                .overlay(
                    RoundedRectangle(cornerRadius: 8)
                        .stroke(Color.gray.opacity(0.3), lineWidth: 1)
                )
            
            VStack(alignment: .leading, spacing: 4) {
                Text(String(describing: color))
                    .font(.headline)
                Text(String(describing: color))
                    .font(.system(.caption, design: .monospaced))
                    .foregroundColor(.secondary)
            }
            
            Spacer()
        }
        .padding(.vertical, 4)
    }
}

/// Visual showcase for Semantic Colors (grouped by category like Figma: bg, fg, stroke, interactive)
@available(iOS 17.0, *)
struct SemanticColorsShowcase: View {
    private static let categoryOrder: [SemanticColorCategory] = [.bg, .fg, .stroke, .interactive]
    
    var body: some View {
        List {
            Section(header: Text("Semantic Colors")) {
                Text("Contextual colors grouped by category (matches Figma)")
                    .font(.caption)
                    .foregroundColor(.secondary)
            }
            
            ForEach(Self.categoryOrder, id: \.self) { category in
                let colorsInCategory = SemanticColors.allCases.filter { $0.category == category }
                if !colorsInCategory.isEmpty {
                    Section(header: HStack {
                        Text(category.rawValue)
                            .font(.subheadline)
                            .fontWeight(.semibold)
                        Spacer()
                        Text("\(colorsInCategory.count)")
                            .font(.system(.caption, design: .monospaced))
                            .foregroundColor(.secondary)
                    }) {
                        ForEach(Array(colorsInCategory), id: \.self) { color in
                            SemanticColorRow(color: color)
                        }
                    }
                }
            }
        }
        .navigationTitle("Semantic Colors")
        .toolbar {
            Text("\(SemanticColors.allCases.count)")
                .font(.system(.body, design: .monospaced))
                .foregroundColor(.secondary)
        }
    }
}

@available(iOS 17.0, *)
struct SemanticColorRow: View {
    let color: SemanticColors
    
    var body: some View {
        HStack(spacing: 16) {
            RoundedRectangle(cornerRadius: 8)
                .fill(Color.semantic(color))
                .frame(width: 60, height: 60)
                .overlay(
                    RoundedRectangle(cornerRadius: 8)
                        .stroke(Color.gray.opacity(0.3), lineWidth: 1)
                )
            
            VStack(alignment: .leading, spacing: 4) {
                Text(String(describing: color))
                    .font(.headline)
                Text(color.rawValue)
                    .font(.system(.caption, design: .monospaced))
                    .foregroundColor(.secondary)
            }
            
            Spacer()
        }
        .padding(.vertical, 4)
    }
}

/// Visual showcase for Gradient Stops (semantic colors for gradients)
@available(iOS 17.0, *)
struct GradientStopsShowcase: View {
    var body: some View {
        List {
            Section(header: Text("Gradient Stops")) {
                Text("Gradient colors with light/dark mode support")
                    .font(.caption)
                    .foregroundColor(.secondary)
            }
            
            Section {
                ForEach(Array(Gradientstops.allCases), id: \.self) { stop in
                    GradientStopRow(stop: stop)
                }
            }
        }
        .navigationTitle("Gradient Stops")
        .toolbar {
            Text("\(Gradientstops.allCases.count)")
                .font(.system(.body, design: .monospaced))
                .foregroundColor(.secondary)
        }
    }
}

@available(iOS 17.0, *)
struct GradientStopRow: View {
    let stop: Gradientstops
    
    var body: some View {
        HStack(spacing: 16) {
            RoundedRectangle(cornerRadius: 8)
                .fill(Color.semantic(stop))
                .frame(width: 60, height: 60)
                .overlay(
                    RoundedRectangle(cornerRadius: 8)
                        .stroke(Color.gray.opacity(0.3), lineWidth: 1)
                )
            
            VStack(alignment: .leading, spacing: 4) {
                Text(String(describing: stop))
                    .font(.headline)
                Text(stop.rawValue)
                    .font(.system(.caption, design: .monospaced))
                    .foregroundColor(.secondary)
            }
            
            Spacer()
        }
        .padding(.vertical, 4)
    }
}

/// Visual showcase for Effects Elevation tokens
@available(iOS 17.0, *)
struct EffectsElevationShowcase: View {
    @Environment(\.colorScheme) var colorScheme
    
    var body: some View {
        List {
            Section {
                VStack(alignment: .leading, spacing: 12) {
                    Text("Elevation System")
                        .font(.title2)
                        .fontWeight(.bold)
                    Text("Pixel-perfect Figma shadows with automatic light/dark mode support")
                        .font(.caption)
                        .foregroundColor(.secondary)
                    
                    HStack(spacing: 12) {
                        Label("Blur ÷ 2", systemImage: "sparkles")
                            .font(.caption)
                            .foregroundColor(.secondary)
                        Label("Spread Simulation", systemImage: "square.stack.3d.up")
                            .font(.caption)
                            .foregroundColor(.secondary)
                    }
                    .padding(.top, 4)
                }
            }
            
            Section(header: Text("Live Examples")) {
                VStack(spacing: 20) {
                    // Show all elevations side by side
                    ScrollView(.horizontal, showsIndicators: false) {
                        HStack(spacing: 16) {
                            ForEach(Array(EffectsElevation.allCases), id: \.self) { elevation in
                                ElevationCard(elevation: elevation)
                            }
                        }
                        .padding(.horizontal, 4)
                    }
                }
                .padding(.vertical, 8)
            }
            
            Section(header: Text("Usage")) {
                VStack(alignment: .leading, spacing: 8) {
                    Text(".elevation(.borderedDefault)")
                        .font(.system(.caption, design: .monospaced))
                        .padding(8)
                        .background(Color.purple.opacity(0.1))
                        .cornerRadius(4)
                    
                    Text("// Automatically adapts to color scheme")
                        .font(.system(.caption, design: .monospaced))
                        .foregroundColor(.secondary)
                        .padding(.leading, 8)
                }
            }
            
            Section(header: Text("All Elevation Styles")) {
                ForEach(Array(EffectsElevation.allCases), id: \.self) { elevation in
                    ElevationStyleRow(elevation: elevation)
                }
            }
        }
        .navigationTitle("Elevation")
        .toolbar {
            Text("\(EffectsElevation.allCases.count)")
                .font(.system(.body, design: .monospaced))
                .foregroundColor(.secondary)
        }
    }
}

@available(iOS 17.0, *)
struct ElevationCard: View {
    let elevation: EffectsElevation
    @Environment(\.colorScheme) var colorScheme
    
    private var elevationName: String {
        let description = String(describing: elevation)
        return description.components(separatedBy: ".").last ?? description
    }
    
    var body: some View {
        VStack(spacing: 8) {
            RoundedRectangle(cornerRadius: 12)
                .fill(Color(UIColor.systemBackground))
                .frame(width: 100, height: 100)
                .elevation(elevation)
                .overlay(
                    VStack {
                        Image(systemName: "square.stack.3d.up.fill")
                            .font(.title2)
                            .foregroundColor(.secondary)
                        Text(elevationName)
                            .font(.caption2)
                            .foregroundColor(.secondary)
                            .multilineTextAlignment(.center)
                            .lineLimit(2)
                    }
                )
            
            Text(elevationName)
                .font(.caption2)
                .foregroundColor(.secondary)
                .multilineTextAlignment(.center)
                .lineLimit(2)
        }
    }
}

@available(iOS 17.0, *)
struct ElevationStyleRow: View {
    let elevation: EffectsElevation
    @Environment(\.colorScheme) var colorScheme
    
    private var elevationName: String {
        let description = String(describing: elevation)
        return description.components(separatedBy: ".").last ?? description
    }
    
    var body: some View {
        VStack(alignment: .leading, spacing: 12) {
            // Visual card with elevation
            HStack {
                RoundedRectangle(cornerRadius: 12)
                    .fill(Color(UIColor.systemBackground))
                    .frame(width: 80, height: 80)
                    .elevation(elevation)
                    .overlay(
                        VStack {
                            Image(systemName: "square.stack.3d.up.fill")
                                .font(.title3)
                                .foregroundColor(.secondary)
                        }
                    )
                
                VStack(alignment: .leading, spacing: 4) {
                    Text(elevationName)
                        .font(.headline)
                    
                    Text(".elevation(.\(elevationName))")
                        .font(.system(.caption, design: .monospaced))
                        .foregroundColor(.secondary)
                }
                
                Spacer()
            }
            
            // Shadow properties
            let style = elevation.theme.style(for: colorScheme)
            VStack(alignment: .leading, spacing: 8) {
                HStack(spacing: 16) {
                    VStack(alignment: .leading, spacing: 2) {
                        Text("Color").font(.caption2).foregroundColor(.secondary)
                        HStack(spacing: 4) {
                            Circle()
                                .fill(style.color)
                                .frame(width: 16, height: 16)
                            Text(style.color.description.components(separatedBy: " ").first ?? "")
                                .font(.system(.caption2, design: .monospaced))
                        }
                    }
                    
                    VStack(alignment: .leading, spacing: 2) {
                        Text("Blur").font(.caption2).foregroundColor(.secondary)
                        Text("\(Int(style.blur))pt")
                            .font(.system(.caption2, design: .monospaced))
                    }
                    
                    if let positionY = style.positionY {
                        VStack(alignment: .leading, spacing: 2) {
                            Text("Y Offset").font(.caption2).foregroundColor(.secondary)
                            Text("\(Int(positionY))pt")
                                .font(.system(.caption2, design: .monospaced))
                        }
                    }
                    
                    if let spread = style.spread {
                        VStack(alignment: .leading, spacing: 2) {
                            Text("Spread").font(.caption2).foregroundColor(.secondary)
                            Text("\(Int(spread))pt")
                                .font(.system(.caption2, design: .monospaced))
                        }
                    }
                }
                
                // Light/Dark mode indicator
                HStack(spacing: 4) {
                    Image(systemName: colorScheme == .dark ? "moon.fill" : "sun.max.fill")
                        .font(.caption2)
                    Text("Current: \(colorScheme == .dark ? "Dark" : "Light") Mode")
                        .font(.caption2)
                }
                .foregroundColor(.secondary)
            }
            .padding(8)
            .background(Color.secondary.opacity(0.05))
            .cornerRadius(6)
        }
        .padding(.vertical, 8)
    }
}

/// Visual showcase for Device & Orientation tokens (4 device types)
@available(iOS 17.0, *)
struct DeviceAndOrientationShowcase: View {
    var body: some View {
        List {
            Section(header: Text("Device & Orientation")) {
                Text("Layout constraints for different devices and orientations")
                    .font(.caption)
                    .foregroundColor(.secondary)
            }
            
            Section(header: Text("Portrait")) {
                ForEach(Array(Portrait.allCases), id: \.self) { token in
                    HStack {
                        Text(String(describing: token))
                            .font(.body)
                        Spacer()
                        Text("\(Int(token.value))pt")
                            .font(.system(.caption, design: .monospaced))
                            .foregroundColor(.secondary)
                    }
                    .padding(.vertical, 4)
                }
            }
            
            Section(header: Text("Landscape")) {
                ForEach(Array(Landscape.allCases), id: \.self) { token in
                    HStack {
                        Text(String(describing: token))
                            .font(.body)
                        Spacer()
                        Text("\(Int(token.value))pt")
                            .font(.system(.caption, design: .monospaced))
                            .foregroundColor(.secondary)
                    }
                    .padding(.vertical, 4)
                }
            }
            
            Section(header: Text("Tablet Portrait")) {
                ForEach(Array(TabletPortrait.allCases), id: \.self) { token in
                    HStack {
                        Text(String(describing: token))
                            .font(.body)
                        Spacer()
                        Text("\(Int(token.value))pt")
                            .font(.system(.caption, design: .monospaced))
                            .foregroundColor(.secondary)
                    }
                    .padding(.vertical, 4)
                }
            }
            
            Section(header: Text("Tablet Landscape")) {
                ForEach(Array(TabletLandscape.allCases), id: \.self) { token in
                    HStack {
                        Text(String(describing: token))
                            .font(.body)
                        Spacer()
                        Text("\(Int(token.value))pt")
                            .font(.system(.caption, design: .monospaced))
                            .foregroundColor(.secondary)
                    }
                    .padding(.vertical, 4)
                }
            }
        }
        .navigationTitle("Device & Orientation")
        .toolbar {
            Text("\(Portrait.allCases.count + Landscape.allCases.count + TabletPortrait.allCases.count + TabletLandscape.allCases.count)")
                .font(.system(.body, design: .monospaced))
                .foregroundColor(.secondary)
        }
    }
}

// MARK: - Generic Token List (Fallback)

@available(iOS 17.0, *)
struct TokenListView<T: CaseIterable>: View {
    let title: String
    let tokens: [T]
    
    init(title: String) {
        self.title = title
        self.tokens = Array(T.allCases)
    }
    
    var body: some View {
        List {
            ForEach(tokens.indices, id: \.self) { index in
                TokenRow(token: tokens[index])
            }
        }
        .navigationTitle(title)
    }
}

@available(iOS 17.0, *)
struct TokenRow<T>: View {
    let token: T
    
    var body: some View {
        VStack(alignment: .leading, spacing: 4) {
            Text(String(describing: token))
                .font(.body)
                .fontWeight(.medium)
            
            if let value = getTokenValue(token) {
                Text("Value: \(value)")
                    .font(.caption)
                    .foregroundColor(.secondary)
            }
        }
        .padding(.vertical, 4)
    }
    
    private func getTokenValue(_ token: T) -> String? {
        let mirror = Mirror(reflecting: token)
        
        // For enums with associated values, try to find 'value' property
        if let child = mirror.children.first {
            if let label = child.label, label == "value" {
                return formatValue(child.value)
            }
            return formatValue(child.value)
        }
        
        return nil
    }
    
    private func formatValue(_ value: Any) -> String {
        if let cgFloat = value as? CGFloat {
            return String(format: "%.1f", cgFloat)
        }
        if let double = value as? Double {
            return String(format: "%.1f", double)
        }
        if let int = value as? Int {
            return "\(int)"
        }
        return String(describing: value)
    }
}

// MARK: - Preview

@available(iOS 17.0, *)
struct TokenShowcaseView_Previews: PreviewProvider {
    static var previews: some View {
        TokenShowcaseView()
    }
}

#endif // os(iOS)
