// Generated by umain-design-tokens-pipeline
// Do not edit this file manually

import SwiftUI
import Foundation
#if canImport(UIKit)
import UIKit
#endif
#if canImport(AppKit)
import AppKit
#endif

// MARK: - TypographyStyle

public struct TypographyStyle {
    public let fontName: String
    public let size: CGFloat
    /// Figma line height value (absolute). Note: SwiftUI's .lineSpacing() is additive,
    /// so we cannot accurately match Figma's absolute line heights without knowing
    /// the font's natural line height. This value is kept for reference only.
    public let lineHeight: CGFloat
    /// Letter spacing as percentage (converted from Figma's point values)
    public let letterSpacingPercent: CGFloat
    
    /// Computed letter spacing in points (converted from percentage)
    /// This works correctly with Dynamic Type scaling.
    public var letterSpacingPoints: CGFloat {
        (letterSpacingPercent / 100.0) * size
    }
}

// MARK: - Typography

public enum Typography: CaseIterable {
    case amount
    case badge
    case button
    case h0
    case h1
    case h2
    case h3
    case h4
    case paragraphMediumBold
    case paragraphMediumLink
    case paragraphMediumRegular
    case paragraphSmallBold
    case paragraphSmallLink
    case paragraphSmallRegular
    case paragraphXsmallBold
    case paragraphXsmallRegular
    case sizeIdle
    case sizeSelected
    case tabbarIdle
    case tabbarSelected
    case titleXl
}

// MARK: - Typography Data

private let typographyData: [Typography: TypographyStyle] = [
    .amount: .init(
        fontName: "YourFont-Regular",
        size: 18.0,
        lineHeight: 22.0,
        letterSpacingPercent: 0.0
    ),
    .badge: .init(
        fontName: "YourFont-Bold",
        size: 12.0,
        lineHeight: 16.0,
        letterSpacingPercent: 0.0
    ),
    .button: .init(
        fontName: "YourFont-Regular",
        size: 15.0,
        lineHeight: 18.0,
        letterSpacingPercent: 0.0
    ),
    .h0: .init(
        fontName: "YourFont-Bold",
        size: 52.0,
        lineHeight: 58.0,
        letterSpacingPercent: -1.75
    ),
    .h1: .init(
        fontName: "YourFont-Bold",
        size: 30.0,
        lineHeight: 33.0,
        letterSpacingPercent: -1.85
    ),
    .h2: .init(
        fontName: "YourFont-Bold",
        size: 22.0,
        lineHeight: 22.0,
        letterSpacingPercent: -2.0
    ),
    .h3: .init(
        fontName: "YourFont-Bold",
        size: 15.0,
        lineHeight: 18.0,
        letterSpacingPercent: -1.75
    ),
    .h4: .init(
        fontName: "YourFont-Bold",
        size: 14.0,
        lineHeight: 16.0,
        letterSpacingPercent: 0.0
    ),
    .paragraphMediumBold: .init(
        fontName: "YourFont-Bold",
        size: 14.0,
        lineHeight: 18.0,
        letterSpacingPercent: 0.0
    ),
    .paragraphMediumLink: .init(
        fontName: "YourFont-Regular",
        size: 14.0,
        lineHeight: 18.0,
        letterSpacingPercent: 0.0
    ),
    .paragraphMediumRegular: .init(
        fontName: "YourFont-Regular",
        size: 14.0,
        lineHeight: 18.0,
        letterSpacingPercent: 0.0
    ),
    .paragraphSmallBold: .init(
        fontName: "YourFont-Bold",
        size: 12.0,
        lineHeight: 15.0,
        letterSpacingPercent: 0.0
    ),
    .paragraphSmallLink: .init(
        fontName: "YourFont-Regular",
        size: 12.0,
        lineHeight: 15.0,
        letterSpacingPercent: 0.0
    ),
    .paragraphSmallRegular: .init(
        fontName: "YourFont-Regular",
        size: 12.0,
        lineHeight: 15.0,
        letterSpacingPercent: 0.0
    ),
    .paragraphXsmallBold: .init(
        fontName: "YourFont-Bold",
        size: 10.0,
        lineHeight: 16.0,
        letterSpacingPercent: 0.0
    ),
    .paragraphXsmallRegular: .init(
        fontName: "YourFont-Regular",
        size: 10.0,
        lineHeight: 16.0,
        letterSpacingPercent: 0.0
    ),
    .sizeIdle: .init(
        fontName: "YourFont-Regular",
        size: 15.0,
        lineHeight: 20.0,
        letterSpacingPercent: 0.0
    ),
    .sizeSelected: .init(
        fontName: "YourFont-Bold",
        size: 15.0,
        lineHeight: 20.0,
        letterSpacingPercent: 0.0
    ),
    .tabbarIdle: .init(
        fontName: "YourFont-Regular",
        size: 8.0,
        lineHeight: 11.0,
        letterSpacingPercent: 0.0
    ),
    .tabbarSelected: .init(
        fontName: "YourFont-Bold",
        size: 8.0,
        lineHeight: 11.0,
        letterSpacingPercent: 0.0
    ),
    .titleXl: .init(
        fontName: "YourFont-Bold",
        size: 72.0,
        lineHeight: 90.0,
        letterSpacingPercent: -1.8
    ),
]

// MARK: - Typography Extension

extension Typography {
    public var style: TypographyStyle {
        typographyData[self]!
    }
    
    /// Returns the Dynamic Type text style for this typography token.
    /// Calculated based on font size according to Apple's Human Interface Guidelines.
    /// This enables automatic scaling with user accessibility settings.
    @available(iOS 17.0, *)
    public var relative: Font.TextStyle {
        switch self {
        case .amount: return .title3
        case .badge: return .caption
        case .button: return .callout
        case .h0: return .largeTitle
        case .h1: return .largeTitle
        case .h2: return .title2
        case .h3: return .headline
        case .h4: return .subheadline
        case .paragraphMediumBold: return .subheadline
        case .paragraphMediumLink: return .subheadline
        case .paragraphMediumRegular: return .subheadline
        case .paragraphSmallBold: return .caption
        case .paragraphSmallLink: return .caption
        case .paragraphSmallRegular: return .caption
        case .paragraphXsmallBold: return .caption2
        case .paragraphXsmallRegular: return .caption2
        case .sizeIdle: return .headline
        case .sizeSelected: return .headline
        case .tabbarIdle: return .caption2
        case .tabbarSelected: return .caption2
        case .titleXl: return .largeTitle
        }
    }
}

// MARK: - TypographyModifier

@available(iOS 17.0, *)
struct TypographyModifier: ViewModifier {
    let typography: Typography
    
    func body(content: Content) -> some View {
        let style = typography.style
        
        // Note: SwiftUI's .lineSpacing() is additive (adds to font's natural line height),
        // while Figma uses absolute line height. We cannot accurately match Figma's absolute
        // line heights without knowing the font's natural line height programmatically.
        // Setting lineSpacing to 0 uses the font's natural line height.
        // If you need to match Figma exactly, you would need to:
        // 1. Measure the font's natural line height for each size
        // 2. Calculate: lineSpacing = figmaLineHeight - naturalLineHeight
        // For now, we use 0 to rely on the font's natural spacing.
        let lineSpacing: CGFloat = 0.0
        
        return content
            .font(.custom(style.fontName, size: style.size, relativeTo: typography.relative))
            .lineSpacing(lineSpacing)
            .tracking(style.letterSpacingPoints)
    }
}

// MARK: - View Extension

@available(iOS 17.0, *)
extension View {
    public func typography(_ type: Typography) -> some View {
        modifier(TypographyModifier(typography: type))
    }
}

// MARK: - Text Extension

@available(iOS 17.0, *)
extension Text {
    public func typography(_ type: Typography) -> some View {
        self.modifier(TypographyModifier(typography: type))
    }
}
