// Generated by UmainDesignToken
// Do not edit this file manually

import SwiftUI
#if canImport(UIKit)
import UIKit
#endif

// MARK: - UiEdges

/// UiEdges tokens.
/// Usage: `UiEdges.l.value`
public enum UiEdges: CGFloat, CaseIterable {
    /// RoundUicomponentl - 48.0
    /// Category: Round
    case roundUicomponentl = 48.0
    /// SharpUicomponentl - 0.0
    /// Category: Sharp
    case sharpUicomponentl = 0.0
    /// RoundUicomponentm - 16.0
    /// Category: Round
    case roundUicomponentm = 16.0
    /// SharpUicomponentm - 0.0
    /// Category: Sharp
    case sharpUicomponentm = 0.0001
    /// RoundUicomponents - 100.0
    /// Category: Round
    case roundUicomponents = 100.0
    /// SharpUicomponents - 0.0
    /// Category: Sharp
    case sharpUicomponents = 0.0002

    /// Returns the numeric value of the token.
    public var value: CGFloat {
        switch self {
        case .roundUicomponentl: return rawValue
        case .sharpUicomponentl: return rawValue
        case .roundUicomponentm: return rawValue
        case .sharpUicomponentm: return 0.0
        case .roundUicomponents: return rawValue
        case .sharpUicomponents: return 0.0
        }
    }
}

