name: Design Tokens Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  process-tokens:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Copy tokens to root directory
      run: |
        # Ensure dispatches directory exists
        mkdir -p dispatches
        
        # Check if dispatches/tokens.json exists, if not create it from root tokens.json
        if [ ! -f "dispatches/tokens.json" ]; then
          echo "dispatches/tokens.json not found, creating from root tokens.json"
          cp tokens.json dispatches/tokens.json
        fi
        
        # Copy the tokens.json file to the root directory to make it visible
        cp dispatches/tokens.json ./tokens.json
        
        # Also create a README for the tokens
        cat > README.md << 'EOF'
        # Design Tokens
        
        This repository contains design tokens for the project.
        
        ## Files
        
        - `tokens.json` - The main design tokens file (automatically generated)
        - `dispatches/tokens.json` - Source tokens file (updated by plugin)
        
        ## Usage
        
        The tokens are automatically processed and made available in the root directory.
        The plugin updates `dispatches/tokens.json` and this workflow copies it to the root.
        EOF
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Check if there are changes to commit
        if git diff --quiet; then
          echo "No changes to commit"
        else
          git add .
          git commit -m "Update design tokens [skip ci]"
          git push origin HEAD:main
        fi
