name: Design Tokens Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  process-tokens:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install Style Dictionary
      run: |
        npm init -y
        npm install style-dictionary
        
    - name: Process tokens with Style Dictionary
      run: |
        # Ensure directories exist
        mkdir -p dispatches
        mkdir -p dist
        mkdir -p config
        
        # Check if dispatches/tokens.json exists, if not create it from root tokens.json
        if [ ! -f "dispatches/tokens.json" ]; then
          echo "dispatches/tokens.json not found, creating from root tokens.json"
          cp tokens.json dispatches/tokens.json
        fi
        
        # Create Style Dictionary configuration
        cat > config/style-dictionary.config.js << 'EOF'
        module.exports = {
          source: ['dispatches/tokens.json'],
          transform: {
            'ios/color': {
              type: 'value',
              matcher: function(token) {
                return token.type === 'color';
              },
              transformer: function(token) {
                // iOS uses UIColor format
                return `UIColor(red: ${token.value}, green: ${token.value}, blue: ${token.value}, alpha: 1.0)`;
              }
            },
            'android/color': {
              type: 'value',
              matcher: function(token) {
                return token.type === 'color';
              },
              transformer: function(token) {
                // Android uses hex format
                return token.value;
              }
            }
          },
          platforms: {
            ios: {
              transformGroup: 'ios',
              transforms: ['ios/color'],
              buildPath: 'dist/ios/',
              files: [
                {
                  destination: 'tokens.json',
                  format: 'json/nested',
                  options: {
                    outputReferences: false
                  }
                },
                {
                  destination: 'tokens.plist',
                  format: 'ios/plist'
                }
              ]
            },
            android: {
              transformGroup: 'android',
              transforms: ['android/color'],
              buildPath: 'dist/android/',
              files: [
                {
                  destination: 'tokens.json',
                  format: 'json/flat',
                  options: {
                    outputReferences: false
                  }
                },
                {
                  destination: 'tokens.xml',
                  format: 'android/xml'
                }
              ]
            }
          }
        };
        EOF
        
        # Run Style Dictionary transformation
        if npx style-dictionary build --config config/style-dictionary.config.js; then
          echo "Style Dictionary transformation successful"
          # Copy iOS tokens to root directory
          cp dist/ios/tokens.json ./tokens-ios.json
          # Copy Android tokens to root directory  
          cp dist/android/tokens.json ./tokens-android.json
          # Copy the main tokens file (use iOS as primary)
          cp dist/ios/tokens.json ./tokens.json
        else
          echo "Style Dictionary failed, using fallback approach"
          # Fallback: just copy the source tokens if Style Dictionary fails
          cp dispatches/tokens.json ./tokens.json
          cp dispatches/tokens.json ./tokens-ios.json
          cp dispatches/tokens.json ./tokens-android.json
        fi
        
        # Also create a README for the tokens
        cat > README.md << 'EOF'
        # Design Tokens
        
        This repository contains design tokens for iOS and Android, automatically processed with Style Dictionary.
        
        ## Files
        
        - `tokens.json` - Main design tokens file (iOS format, automatically generated)
        - `tokens-ios.json` - iOS-specific design tokens (JSON format)
        - `tokens-android.json` - Android-specific design tokens (JSON format)
        - `dispatches/tokens.json` - Source tokens file (updated by plugin)
        - `dist/ios/` - iOS build output (JSON + PLIST formats)
        - `dist/android/` - Android build output (JSON + XML formats)
        
        ## Formats
        
        - **iOS**: JSON nested format + PLIST for iOS development (UIColor format)
        - **Android**: JSON flat format + XML for Android development (hex format)
        - **Source Format**: Original plugin format for editing
        
        ## Usage
        
        The tokens are automatically processed with Style Dictionary for iOS and Android platforms.
        The plugin updates `dispatches/tokens.json` and this workflow transforms them for mobile development.
        EOF
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Check if there are changes to commit
        if git diff --quiet; then
          echo "No changes to commit"
        else
          git add .
          git commit -m "Update design tokens (DTCG format) [skip ci]"
          git push origin HEAD:main
        fi
