name: Design Tokens Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  process-tokens:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install Style Dictionary
      run: |
        npm init -y
        npm install style-dictionary
        
    - name: Process tokens with Style Dictionary
      run: |
        # Ensure directories exist
        mkdir -p dispatches
        mkdir -p dist
        mkdir -p config
        
        # Check if dispatches/tokens.json exists, if not create it from root tokens.json
        if [ ! -f "dispatches/tokens.json" ]; then
          echo "dispatches/tokens.json not found, creating from root tokens.json"
          cp tokens.json dispatches/tokens.json
        fi
        
        # Create Style Dictionary configuration
        cat > config/style-dictionary.config.js << 'EOF'
        module.exports = {
          source: ['dispatches/tokens.json'],
          platforms: {
            web: {
              transformGroup: 'web',
              buildPath: 'dist/',
              files: [
                {
                  destination: 'tokens.json',
                  format: 'json/flat',
                  options: {
                    outputReferences: false
                  }
                },
                {
                  destination: 'tokens-nested.json',
                  format: 'json/nested',
                  options: {
                    outputReferences: false
                  }
                },
                {
                  destination: 'tokens-css.json',
                  format: 'css/variables',
                  options: {
                    outputReferences: false
                  }
                }
              ]
            }
          }
        };
        EOF
        
        # Run Style Dictionary transformation
        if npx style-dictionary build --config config/style-dictionary.config.js; then
          echo "Style Dictionary transformation successful"
          # Copy the transformed tokens to root directory
          cp dist/tokens.json ./tokens.json
        else
          echo "Style Dictionary failed, using fallback approach"
          # Fallback: just copy the source tokens if Style Dictionary fails
          cp dispatches/tokens.json ./tokens.json
          # Create a simple nested version
          cp dispatches/tokens.json ./dist/tokens-nested.json
          # Create a basic CSS variables file
          echo "/* Design Tokens - CSS Variables */" > ./dist/tokens-css.json
          echo "/* Generated from dispatches/tokens.json */" >> ./dist/tokens-css.json
        fi
        
        # Also create a README for the tokens
        cat > README.md << 'EOF'
        # Design Tokens
        
        This repository contains design tokens for the project, automatically processed with Style Dictionary.
        
        ## Files
        
        - `tokens.json` - Main design tokens file (flat JSON, automatically generated)
        - `tokens-nested.json` - Nested JSON format for better structure
        - `tokens-css.json` - CSS custom properties format
        - `dispatches/tokens.json` - Source tokens file (updated by plugin)
        - `dist/` - Build output directory with all transformed formats
        
        ## Formats
        
        - **JSON Flat**: Flattened structure for easy consumption
        - **JSON Nested**: Hierarchical structure for better organization
        - **CSS Variables**: Ready-to-use CSS custom properties
        - **Source Format**: Original plugin format for editing
        
        ## Usage
        
        The tokens are automatically processed with Style Dictionary and made available in multiple formats.
        The plugin updates `dispatches/tokens.json` and this workflow transforms them using Style Dictionary.
        EOF
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Check if there are changes to commit
        if git diff --quiet; then
          echo "No changes to commit"
        else
          git add .
          git commit -m "Update design tokens (DTCG format) [skip ci]"
          git push origin HEAD:main
        fi
